// Code generated by scripts/generate_biomes.go; DO NOT EDIT.
// This file was generated by robots at
// 2020-10-06 03:16:10.310621

package biome

var Ocean = &Biome{
	Id: 0,
	Name: "ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var Plains = &Biome{
	Id: 1,
	Name: "plains",
	Type: TypePlains,
	Rainfall: 0.4,
	Temperature: 0.8,
}
var Desert = &Biome{
	Id: 2,
	Name: "desert",
	Type: TypeDesert,
	Rainfall: 0,
	Temperature: 2,
}
var Mountains = &Biome{
	Id: 3,
	Name: "mountains",
	Type: TypeHills,
	Rainfall: 0.3,
	Temperature: 0.2,
}
var Forest = &Biome{
	Id: 4,
	Name: "forest",
	Type: TypeForest,
	Rainfall: 0.8,
	Temperature: 0.7,
}
var Taiga = &Biome{
	Id: 5,
	Name: "taiga",
	Type: TypeTaiga,
	Rainfall: 0.8,
	Temperature: 0.25,
}
var Swamp = &Biome{
	Id: 6,
	Name: "swamp",
	Type: TypeSwamp,
	Rainfall: 0.9,
	Temperature: 0.8,
}
var River = &Biome{
	Id: 7,
	Name: "river",
	Type: TypeRiver,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var Nether = &Biome{
	Id: 8,
	Name: "nether",
	Type: TypeNether,
	Rainfall: 0,
	Temperature: 2,
}
var TheEnd = &Biome{
	Id: 9,
	Name: "the_end",
	Type: TypeSky,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var FrozenOcean = &Biome{
	Id: 10,
	Name: "frozen_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0,
}
var FrozenRiver = &Biome{
	Id: 11,
	Name: "frozen_river",
	Type: TypeRiver,
	Rainfall: 0.5,
	Temperature: 0,
}
var SnowyTundra = &Biome{
	Id: 12,
	Name: "snowy_tundra",
	Type: TypeSnow,
	Rainfall: 0.5,
	Temperature: 0,
}
var SnowyMountains = &Biome{
	Id: 13,
	Name: "snowy_mountains",
	Type: TypeSnow,
	Rainfall: 0.5,
	Temperature: 0,
}
var MushroomFields = &Biome{
	Id: 14,
	Name: "mushroom_fields",
	Type: TypeMushroomIsland,
	Rainfall: 1,
	Temperature: 0.9,
}
var MushroomFieldShore = &Biome{
	Id: 15,
	Name: "mushroom_field_shore",
	Type: TypeMushroomIsland,
	Rainfall: 1,
	Temperature: 0.9,
}
var Beach = &Biome{
	Id: 16,
	Name: "beach",
	Type: TypeBeach,
	Rainfall: 0.4,
	Temperature: 0.8,
}
var DesertHills = &Biome{
	Id: 17,
	Name: "desert_hills",
	Type: TypeHills,
	Rainfall: 0,
	Temperature: 2,
}
var WoodedHills = &Biome{
	Id: 18,
	Name: "wooded_hills",
	Type: TypeHills,
	Rainfall: 0.8,
	Temperature: 0.7,
}
var TaigaHills = &Biome{
	Id: 19,
	Name: "taiga_hills",
	Type: TypeHills,
	Rainfall: 0.8,
	Temperature: 0.25,
}
var MountainEdge = &Biome{
	Id: 20,
	Name: "mountain_edge",
	Type: TypeHills,
	Rainfall: 0.3,
	Temperature: 0.2,
}
var Jungle = &Biome{
	Id: 21,
	Name: "jungle",
	Type: TypeJungle,
	Rainfall: 0.9,
	Temperature: 0.95,
}
var JungleHills = &Biome{
	Id: 22,
	Name: "jungle_hills",
	Type: TypeHills,
	Rainfall: 0.9,
	Temperature: 0.95,
}
var JungleEdge = &Biome{
	Id: 23,
	Name: "jungle_edge",
	Type: TypeJungle,
	Rainfall: 0.8,
	Temperature: 0.95,
}
var DeepOcean = &Biome{
	Id: 24,
	Name: "deep_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var StoneShore = &Biome{
	Id: 25,
	Name: "stone_shore",
	Type: TypeStoneBeach,
	Rainfall: 0.3,
	Temperature: 0.2,
}
var SnowyBeach = &Biome{
	Id: 26,
	Name: "snowy_beach",
	Type: TypeSnow,
	Rainfall: 0.3,
	Temperature: 0.05,
}
var BirchForest = &Biome{
	Id: 27,
	Name: "birch_forest",
	Type: TypeForest,
	Rainfall: 0.6,
	Temperature: 0.6,
}
var BirchForestHills = &Biome{
	Id: 28,
	Name: "birch_forest_hills",
	Type: TypeHills,
	Rainfall: 0.6,
	Temperature: 0.6,
}
var DarkForest = &Biome{
	Id: 29,
	Name: "dark_forest",
	Type: TypeForest,
	Rainfall: 0.8,
	Temperature: 0.7,
}
var SnowyTaiga = &Biome{
	Id: 30,
	Name: "snowy_taiga",
	Type: TypeTaiga,
	Rainfall: 0.4,
	Temperature: -0.5,
}
var SnowyTaigaHills = &Biome{
	Id: 31,
	Name: "snowy_taiga_hills",
	Type: TypeHills,
	Rainfall: 0.4,
	Temperature: -0.5,
}
var GiantTreeTaiga = &Biome{
	Id: 32,
	Name: "giant_tree_taiga",
	Type: TypeTaiga,
	Rainfall: 0.8,
	Temperature: 0.3,
}
var GiantTreeTaigaHills = &Biome{
	Id: 33,
	Name: "giant_tree_taiga_hills",
	Type: TypeHills,
	Rainfall: 0.8,
	Temperature: 0.3,
}
var WoodedMountains = &Biome{
	Id: 34,
	Name: "wooded_mountains",
	Type: TypeHills,
	Rainfall: 0.3,
	Temperature: 0.2,
}
var Savanna = &Biome{
	Id: 35,
	Name: "savanna",
	Type: TypeSavanna,
	Rainfall: 0,
	Temperature: 1.2,
}
var SavannaPlateau = &Biome{
	Id: 36,
	Name: "savanna_plateau",
	Type: TypeSavanna,
	Rainfall: 0,
	Temperature: 1,
}
var Badlands = &Biome{
	Id: 37,
	Name: "badlands",
	Type: TypeMesa,
	Rainfall: 0,
	Temperature: 2,
}
var WoodedBadlandsPlateau = &Biome{
	Id: 38,
	Name: "wooded_badlands_plateau",
	Type: TypeMesa,
	Rainfall: 0,
	Temperature: 2,
}
var BadlandsPlateau = &Biome{
	Id: 39,
	Name: "badlands_plateau",
	Type: TypeMesa,
	Rainfall: 0,
	Temperature: 2,
}
var SmallEndIslands = &Biome{
	Id: 40,
	Name: "small_end_islands",
	Type: TypeSky,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var EndMidlands = &Biome{
	Id: 41,
	Name: "end_midlands",
	Type: TypeSky,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var EndHighlands = &Biome{
	Id: 42,
	Name: "end_highlands",
	Type: TypeSky,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var EndBarrens = &Biome{
	Id: 43,
	Name: "end_barrens",
	Type: TypeSky,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var WarmOcean = &Biome{
	Id: 44,
	Name: "warm_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var LukewarmOcean = &Biome{
	Id: 45,
	Name: "lukewarm_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var ColdOcean = &Biome{
	Id: 46,
	Name: "cold_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var DeepWarmOcean = &Biome{
	Id: 47,
	Name: "deep_warm_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var DeepLukewarmOcean = &Biome{
	Id: 48,
	Name: "deep_lukewarm_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var DeepColdOcean = &Biome{
	Id: 49,
	Name: "deep_cold_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var DeepFrozenOcean = &Biome{
	Id: 50,
	Name: "deep_frozen_ocean",
	Type: TypeOcean,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var TheVoid = &Biome{
	Id: 127,
	Name: "the_void",
	Type: TypeVoid,
	Rainfall: 0.5,
	Temperature: 0.5,
}
var SunflowerPlains = &Biome{
	Id: 129,
	Name: "sunflower_plains",
	Type: TypePlains,
	Rainfall: 0.4,
	Temperature: 0.8,
}
var DesertLakes = &Biome{
	Id: 130,
	Name: "desert_lakes",
	Type: TypeDesert,
	Rainfall: 0,
	Temperature: 2,
}
var GravellyMountains = &Biome{
	Id: 131,
	Name: "gravelly_mountains",
	Type: TypeHills,
	Rainfall: 0.3,
	Temperature: 0.2,
}
var FlowerForest = &Biome{
	Id: 132,
	Name: "flower_forest",
	Type: TypeForest,
	Rainfall: 0.8,
	Temperature: 0.7,
}
var TaigaMountains = &Biome{
	Id: 133,
	Name: "taiga_mountains",
	Type: TypeTaiga,
	Rainfall: 0.8,
	Temperature: 0.25,
}
var SwampHills = &Biome{
	Id: 134,
	Name: "swamp_hills",
	Type: TypeHills,
	Rainfall: 0.9,
	Temperature: 0.8,
}
var IceSpikes = &Biome{
	Id: 140,
	Name: "ice_spikes",
	Type: TypeSnow,
	Rainfall: 0.5,
	Temperature: 0,
}
var ModifiedJungle = &Biome{
	Id: 149,
	Name: "modified_jungle",
	Type: TypeJungle,
	Rainfall: 0.9,
	Temperature: 0.95,
}
var ModifiedJungleEdge = &Biome{
	Id: 151,
	Name: "modified_jungle_edge",
	Type: TypeJungle,
	Rainfall: 0.8,
	Temperature: 0.95,
}
var TallBirchForest = &Biome{
	Id: 155,
	Name: "tall_birch_forest",
	Type: TypeForest,
	Rainfall: 0.6,
	Temperature: 0.6,
}
var TallBirchHills = &Biome{
	Id: 156,
	Name: "tall_birch_hills",
	Type: TypeHills,
	Rainfall: 0.6,
	Temperature: 0.6,
}
var DarkForestHills = &Biome{
	Id: 157,
	Name: "dark_forest_hills",
	Type: TypeHills,
	Rainfall: 0.8,
	Temperature: 0.7,
}
var SnowyTaigaMountains = &Biome{
	Id: 158,
	Name: "snowy_taiga_mountains",
	Type: TypeTaiga,
	Rainfall: 0.4,
	Temperature: -0.5,
}
var GiantSpruceTaiga = &Biome{
	Id: 160,
	Name: "giant_spruce_taiga",
	Type: TypeTaiga,
	Rainfall: 0.8,
	Temperature: 0.25,
}
var GiantSpruceTaigaHills = &Biome{
	Id: 161,
	Name: "giant_spruce_taiga_hills",
	Type: TypeHills,
	Rainfall: 0.8,
	Temperature: 0.25,
}
var ModifiedGravellyMountains = &Biome{
	Id: 162,
	Name: "modified_gravelly_mountains",
	Type: TypeHills,
	Rainfall: 0.3,
	Temperature: 0.2,
}
var ShatteredSavanna = &Biome{
	Id: 163,
	Name: "shattered_savanna",
	Type: TypeSavanna,
	Rainfall: 0,
	Temperature: 1.1,
}
var ShatteredSavannaPlateau = &Biome{
	Id: 164,
	Name: "shattered_savanna_plateau",
	Type: TypeSavanna,
	Rainfall: 0,
	Temperature: 1,
}
var ErodedBadlands = &Biome{
	Id: 165,
	Name: "eroded_badlands",
	Type: TypeMesa,
	Rainfall: 0,
	Temperature: 2,
}
var ModifiedWoodedBadlandsPlateau = &Biome{
	Id: 166,
	Name: "modified_wooded_badlands_plateau",
	Type: TypeMesa,
	Rainfall: 0,
	Temperature: 2,
}
var ModifiedBadlandsPlateau = &Biome{
	Id: 167,
	Name: "modified_badlands_plateau",
	Type: TypeMesa,
	Rainfall: 0,
	Temperature: 2,
}
var BambooJungle = &Biome{
	Id: 168,
	Name: "bamboo_jungle",
	Type: TypeJungle,
	Rainfall: 0.9,
	Temperature: 0.95,
}
var BambooJungleHills = &Biome{
	Id: 169,
	Name: "bamboo_jungle_hills",
	Type: TypeHills,
	Rainfall: 0.9,
	Temperature: 0.95,
}

var biomes = [...]*Biome{
	0: Ocean,
	1: Plains,
	2: Desert,
	3: Mountains,
	4: Forest,
	5: Taiga,
	6: Swamp,
	7: River,
	8: Nether,
	9: TheEnd,
	10: FrozenOcean,
	11: FrozenRiver,
	12: SnowyTundra,
	13: SnowyMountains,
	14: MushroomFields,
	15: MushroomFieldShore,
	16: Beach,
	17: DesertHills,
	18: WoodedHills,
	19: TaigaHills,
	20: MountainEdge,
	21: Jungle,
	22: JungleHills,
	23: JungleEdge,
	24: DeepOcean,
	25: StoneShore,
	26: SnowyBeach,
	27: BirchForest,
	28: BirchForestHills,
	29: DarkForest,
	30: SnowyTaiga,
	31: SnowyTaigaHills,
	32: GiantTreeTaiga,
	33: GiantTreeTaigaHills,
	34: WoodedMountains,
	35: Savanna,
	36: SavannaPlateau,
	37: Badlands,
	38: WoodedBadlandsPlateau,
	39: BadlandsPlateau,
	40: SmallEndIslands,
	41: EndMidlands,
	42: EndHighlands,
	43: EndBarrens,
	44: WarmOcean,
	45: LukewarmOcean,
	46: ColdOcean,
	47: DeepWarmOcean,
	48: DeepLukewarmOcean,
	49: DeepColdOcean,
	50: DeepFrozenOcean,
	127: TheVoid,
	129: SunflowerPlains,
	130: DesertLakes,
	131: GravellyMountains,
	132: FlowerForest,
	133: TaigaMountains,
	134: SwampHills,
	140: IceSpikes,
	149: ModifiedJungle,
	151: ModifiedJungleEdge,
	155: TallBirchForest,
	156: TallBirchHills,
	157: DarkForestHills,
	158: SnowyTaigaMountains,
	160: GiantSpruceTaiga,
	161: GiantSpruceTaigaHills,
	162: ModifiedGravellyMountains,
	163: ShatteredSavanna,
	164: ShatteredSavannaPlateau,
	165: ErodedBadlands,
	166: ModifiedWoodedBadlandsPlateau,
	167: ModifiedBadlandsPlateau,
	168: BambooJungle,
	169: BambooJungleHills,
}

