// Code generated by scripts/generate_meta.go; DO NOT EDIT.
// This file was generated by robots at
// 2020-10-09 18:54:01.880886

package block

import "github.com/itay2805/mcserver/minecraft"

type StairsMeta struct {
	Facing minecraft.Face
	Half minecraft.Face
	Shape minecraft.Shape
	Waterlogged bool
}

func (m *StairsMeta) FromMeta(meta uint16) {
	m.Waterlogged = (meta % 2) == 1
	meta /= 2
	m.Shape = minecraft.Shape(meta % 5)
	meta /= 5
	m.Half = minecraft.Face(meta % 2)
	meta /= 2
	m.Facing = minecraft.Face((meta % 4) + 2)
	meta /= 4
}

func (m *StairsMeta) ToMeta() uint16 {
	meta := uint16(0)
	meta *= 4
	meta += uint16(m.Facing) - 2
	meta *= 2
	meta += uint16(m.Half)
	meta *= 5
	meta += uint16(m.Shape)
	meta *= 2
	meta += boolToMeta(m.Waterlogged)
	return meta
}

type FurnaceMeta struct {
	Facing minecraft.Face
	Lit bool
}

func (m *FurnaceMeta) FromMeta(meta uint16) {
	m.Lit = (meta % 2) == 1
	meta /= 2
	m.Facing = minecraft.Face((meta % 4) + 2)
	meta /= 4
}

func (m *FurnaceMeta) ToMeta() uint16 {
	meta := uint16(0)
	meta *= 4
	meta += uint16(m.Facing) - 2
	meta *= 2
	meta += boolToMeta(m.Lit)
	return meta
}

