from ctypes import *
from datetime import datetime
import os.path as path
import urllib.request
import json

# TODO: switch to using go:generate

# This has all of the data we need
import stringcase

with urllib.request.urlopen("https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.15.2/blocks.json") as f:
    blocks = json.load(f)

print("// Code generated by scripts/generate_blocks.go; DO NOT EDIT.")
print("// This file was generated by robots at")
print("// " + str(datetime.now()))
print()

print("package block")
print()
for block in blocks:
    name = stringcase.pascalcase(block['name'])
    print(f"var {name} = &Block{{")
    print(f"\tId: {block['id']},")
    print(f"\tName: \"{block['name']}\",")
    print(f"\tDefaultStateId: {block['defaultState']},")
    print(f"\tSolid: {'false' if block['boundingBox'] == 'nullprovider' else 'true'},")
    print(f"\tTransparent: {'true' if block['transparent'] else 'false'},")
    print(f"\tFilterLight: {block['filterLight']},")
    print(f"\tEmitLight: {block['emitLight']},")
    print("}")
print()

print("var blocks = [...]*Block{")
for block in blocks:
    name = stringcase.pascalcase(block['name'])
    print(f"\t{block['id']}: {name},")
print("}")
print("")

print("var stateIdToBlockId = [...]*Block{")
for block in blocks:
    for i in range(block['minStateId'], block['maxStateId']):
        print(f"\tblocks[{block['id']}],")
print("}")
print("")
