from ctypes import *
from datetime import datetime
import os.path as path
import urllib.request
import json

# TODO: switch to using go:generate

# This has all of the data we need
with urllib.request.urlopen("https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.15.2/entities.json") as f:
    entities = json.load(f)

print("// Code generated by scripts/generate_entities.go; DO NOT EDIT.")
print("// This file was generated by robots at")
print("// " + str(datetime.now()))
print()

print("package entity")
print()
print("var types = [...]Type{")
for entity in entities:
    print(f"\t{entity['id']}: {{")
    print(f"\t\tId: {entity['id']},")
    print(f"\t\tName: \"{entity['name']}\",")
    print(f"\t\tWidth: {entity['width']},")
    print(f"\t\tHeight: {entity['height']},")
    print("\t},")
print("}")
print()
print("var byName = map[string]*Type{")
for entity in entities:
    print(f"\t\"{entity['name']}\": &types[{entity['id']}],")
print("}")
print()
