from ctypes import *
from datetime import datetime
import os.path as path
import urllib.request
import json

# TODO: switch to using go:generate

# This has all of the data we need
import stringcase

with urllib.request.urlopen("https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.15.2/blocks.json") as f:
    blocks = json.load(f)

with urllib.request.urlopen("https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.15.2/items.json") as f:
    items = json.load(f)


block_by_name = {}
for block in blocks:
    block_by_name[block['name']] = block

item_by_name = {}
for item in items:
    item_by_name[item['name']] = item


print("// Code generated by scripts/generate_blocks.go; DO NOT EDIT.")
print("// This file was generated by robots at")
print("// " + str(datetime.now()))
print()

print("package block")
print()
print('import "github.com/itay2805/mcserver/minecraft/item"')
print()

# Block variables
for block in blocks:
    name = stringcase.pascalcase(block['name'])
    print(f"var {name} = &Block{{")
    print(f"\tId: {block['id']},")
    print(f"\tName: \"{block['name']}\",")
    print(f"\tMinStateId: {block['minStateId']},")
    print(f"\tMaxStateId: {block['maxStateId']},")
    print(f"\tDefaultStateId: {block['defaultState']},")
    print(f"\tSolid: {'false' if block['boundingBox'] == 'empty' else 'true'},")
    print(f"\tTransparent: {'true' if block['transparent'] else 'false'},")
    print(f"\tFilterLight: {block['filterLight']},")
    print(f"\tEmitLight: {block['emitLight']},")
    if block['name'] in item_by_name:
        print(f"\tItem: item.{name},")
    print("}")
print()

# Block by id lookup
print("var blocks = [...]*Block{")
for block in blocks:
    name = stringcase.pascalcase(block['name'])
    print(f"\t{block['id']}: {name},")
print("}")
print("")

# Block by state id lookup
print("var stateIdToBlockId = [...]*Block{")
for block in blocks:
    for i in range(block['minStateId'], block['maxStateId']):
        print(f"\tblocks[{block['id']}],")
print("}")
print("")

# Block by item id
print("var blockByItemId = [...]*Block{")
for item in items:
    if item['name'] in block_by_name:
        name = stringcase.pascalcase(item['name'])
        print(f"\t{item['id']}: {name},")
print("}")
print("")
