// Code generated by scripts/generate_items.go; DO NOT EDIT.
// This file was generated by robots at
// 2020-10-08 18:13:59.048446

package item

var Air = &Item{
	ID: 0,
	Name: "air",
	StackSize: 0,
}
var Stone = &Item{
	ID: 1,
	Name: "stone",
	StackSize: 64,
}
var Granite = &Item{
	ID: 2,
	Name: "granite",
	StackSize: 64,
}
var PolishedGranite = &Item{
	ID: 3,
	Name: "polished_granite",
	StackSize: 64,
}
var Diorite = &Item{
	ID: 4,
	Name: "diorite",
	StackSize: 64,
}
var PolishedDiorite = &Item{
	ID: 5,
	Name: "polished_diorite",
	StackSize: 64,
}
var Andesite = &Item{
	ID: 6,
	Name: "andesite",
	StackSize: 64,
}
var PolishedAndesite = &Item{
	ID: 7,
	Name: "polished_andesite",
	StackSize: 64,
}
var GrassBlock = &Item{
	ID: 8,
	Name: "grass_block",
	StackSize: 64,
}
var Dirt = &Item{
	ID: 9,
	Name: "dirt",
	StackSize: 64,
}
var CoarseDirt = &Item{
	ID: 10,
	Name: "coarse_dirt",
	StackSize: 64,
}
var Podzol = &Item{
	ID: 11,
	Name: "podzol",
	StackSize: 64,
}
var Cobblestone = &Item{
	ID: 12,
	Name: "cobblestone",
	StackSize: 64,
}
var OakPlanks = &Item{
	ID: 13,
	Name: "oak_planks",
	StackSize: 64,
}
var SprucePlanks = &Item{
	ID: 14,
	Name: "spruce_planks",
	StackSize: 64,
}
var BirchPlanks = &Item{
	ID: 15,
	Name: "birch_planks",
	StackSize: 64,
}
var JunglePlanks = &Item{
	ID: 16,
	Name: "jungle_planks",
	StackSize: 64,
}
var AcaciaPlanks = &Item{
	ID: 17,
	Name: "acacia_planks",
	StackSize: 64,
}
var DarkOakPlanks = &Item{
	ID: 18,
	Name: "dark_oak_planks",
	StackSize: 64,
}
var OakSapling = &Item{
	ID: 19,
	Name: "oak_sapling",
	StackSize: 64,
}
var SpruceSapling = &Item{
	ID: 20,
	Name: "spruce_sapling",
	StackSize: 64,
}
var BirchSapling = &Item{
	ID: 21,
	Name: "birch_sapling",
	StackSize: 64,
}
var JungleSapling = &Item{
	ID: 22,
	Name: "jungle_sapling",
	StackSize: 64,
}
var AcaciaSapling = &Item{
	ID: 23,
	Name: "acacia_sapling",
	StackSize: 64,
}
var DarkOakSapling = &Item{
	ID: 24,
	Name: "dark_oak_sapling",
	StackSize: 64,
}
var Bedrock = &Item{
	ID: 25,
	Name: "bedrock",
	StackSize: 64,
}
var Sand = &Item{
	ID: 26,
	Name: "sand",
	StackSize: 64,
}
var RedSand = &Item{
	ID: 27,
	Name: "red_sand",
	StackSize: 64,
}
var Gravel = &Item{
	ID: 28,
	Name: "gravel",
	StackSize: 64,
}
var GoldOre = &Item{
	ID: 29,
	Name: "gold_ore",
	StackSize: 64,
}
var IronOre = &Item{
	ID: 30,
	Name: "iron_ore",
	StackSize: 64,
}
var CoalOre = &Item{
	ID: 31,
	Name: "coal_ore",
	StackSize: 64,
}
var OakLog = &Item{
	ID: 32,
	Name: "oak_log",
	StackSize: 64,
}
var SpruceLog = &Item{
	ID: 33,
	Name: "spruce_log",
	StackSize: 64,
}
var BirchLog = &Item{
	ID: 34,
	Name: "birch_log",
	StackSize: 64,
}
var JungleLog = &Item{
	ID: 35,
	Name: "jungle_log",
	StackSize: 64,
}
var AcaciaLog = &Item{
	ID: 36,
	Name: "acacia_log",
	StackSize: 64,
}
var DarkOakLog = &Item{
	ID: 37,
	Name: "dark_oak_log",
	StackSize: 64,
}
var StrippedOakLog = &Item{
	ID: 38,
	Name: "stripped_oak_log",
	StackSize: 64,
}
var StrippedSpruceLog = &Item{
	ID: 39,
	Name: "stripped_spruce_log",
	StackSize: 64,
}
var StrippedBirchLog = &Item{
	ID: 40,
	Name: "stripped_birch_log",
	StackSize: 64,
}
var StrippedJungleLog = &Item{
	ID: 41,
	Name: "stripped_jungle_log",
	StackSize: 64,
}
var StrippedAcaciaLog = &Item{
	ID: 42,
	Name: "stripped_acacia_log",
	StackSize: 64,
}
var StrippedDarkOakLog = &Item{
	ID: 43,
	Name: "stripped_dark_oak_log",
	StackSize: 64,
}
var StrippedOakWood = &Item{
	ID: 44,
	Name: "stripped_oak_wood",
	StackSize: 64,
}
var StrippedSpruceWood = &Item{
	ID: 45,
	Name: "stripped_spruce_wood",
	StackSize: 64,
}
var StrippedBirchWood = &Item{
	ID: 46,
	Name: "stripped_birch_wood",
	StackSize: 64,
}
var StrippedJungleWood = &Item{
	ID: 47,
	Name: "stripped_jungle_wood",
	StackSize: 64,
}
var StrippedAcaciaWood = &Item{
	ID: 48,
	Name: "stripped_acacia_wood",
	StackSize: 64,
}
var StrippedDarkOakWood = &Item{
	ID: 49,
	Name: "stripped_dark_oak_wood",
	StackSize: 64,
}
var OakWood = &Item{
	ID: 50,
	Name: "oak_wood",
	StackSize: 64,
}
var SpruceWood = &Item{
	ID: 51,
	Name: "spruce_wood",
	StackSize: 64,
}
var BirchWood = &Item{
	ID: 52,
	Name: "birch_wood",
	StackSize: 64,
}
var JungleWood = &Item{
	ID: 53,
	Name: "jungle_wood",
	StackSize: 64,
}
var AcaciaWood = &Item{
	ID: 54,
	Name: "acacia_wood",
	StackSize: 64,
}
var DarkOakWood = &Item{
	ID: 55,
	Name: "dark_oak_wood",
	StackSize: 64,
}
var OakLeaves = &Item{
	ID: 56,
	Name: "oak_leaves",
	StackSize: 64,
}
var SpruceLeaves = &Item{
	ID: 57,
	Name: "spruce_leaves",
	StackSize: 64,
}
var BirchLeaves = &Item{
	ID: 58,
	Name: "birch_leaves",
	StackSize: 64,
}
var JungleLeaves = &Item{
	ID: 59,
	Name: "jungle_leaves",
	StackSize: 64,
}
var AcaciaLeaves = &Item{
	ID: 60,
	Name: "acacia_leaves",
	StackSize: 64,
}
var DarkOakLeaves = &Item{
	ID: 61,
	Name: "dark_oak_leaves",
	StackSize: 64,
}
var Sponge = &Item{
	ID: 62,
	Name: "sponge",
	StackSize: 64,
}
var WetSponge = &Item{
	ID: 63,
	Name: "wet_sponge",
	StackSize: 64,
}
var Glass = &Item{
	ID: 64,
	Name: "glass",
	StackSize: 64,
}
var LapisOre = &Item{
	ID: 65,
	Name: "lapis_ore",
	StackSize: 64,
}
var LapisBlock = &Item{
	ID: 66,
	Name: "lapis_block",
	StackSize: 64,
}
var Dispenser = &Item{
	ID: 67,
	Name: "dispenser",
	StackSize: 64,
}
var Sandstone = &Item{
	ID: 68,
	Name: "sandstone",
	StackSize: 64,
}
var ChiseledSandstone = &Item{
	ID: 69,
	Name: "chiseled_sandstone",
	StackSize: 64,
}
var CutSandstone = &Item{
	ID: 70,
	Name: "cut_sandstone",
	StackSize: 64,
}
var NoteBlock = &Item{
	ID: 71,
	Name: "note_block",
	StackSize: 64,
}
var PoweredRail = &Item{
	ID: 72,
	Name: "powered_rail",
	StackSize: 64,
}
var DetectorRail = &Item{
	ID: 73,
	Name: "detector_rail",
	StackSize: 64,
}
var StickyPiston = &Item{
	ID: 74,
	Name: "sticky_piston",
	StackSize: 64,
}
var Cobweb = &Item{
	ID: 75,
	Name: "cobweb",
	StackSize: 64,
}
var Grass = &Item{
	ID: 76,
	Name: "grass",
	StackSize: 64,
}
var Fern = &Item{
	ID: 77,
	Name: "fern",
	StackSize: 64,
}
var DeadBush = &Item{
	ID: 78,
	Name: "dead_bush",
	StackSize: 64,
}
var Seagrass = &Item{
	ID: 79,
	Name: "seagrass",
	StackSize: 64,
}
var SeaPickle = &Item{
	ID: 80,
	Name: "sea_pickle",
	StackSize: 64,
}
var Piston = &Item{
	ID: 81,
	Name: "piston",
	StackSize: 64,
}
var WhiteWool = &Item{
	ID: 82,
	Name: "white_wool",
	StackSize: 64,
}
var OrangeWool = &Item{
	ID: 83,
	Name: "orange_wool",
	StackSize: 64,
}
var MagentaWool = &Item{
	ID: 84,
	Name: "magenta_wool",
	StackSize: 64,
}
var LightBlueWool = &Item{
	ID: 85,
	Name: "light_blue_wool",
	StackSize: 64,
}
var YellowWool = &Item{
	ID: 86,
	Name: "yellow_wool",
	StackSize: 64,
}
var LimeWool = &Item{
	ID: 87,
	Name: "lime_wool",
	StackSize: 64,
}
var PinkWool = &Item{
	ID: 88,
	Name: "pink_wool",
	StackSize: 64,
}
var GrayWool = &Item{
	ID: 89,
	Name: "gray_wool",
	StackSize: 64,
}
var LightGrayWool = &Item{
	ID: 90,
	Name: "light_gray_wool",
	StackSize: 64,
}
var CyanWool = &Item{
	ID: 91,
	Name: "cyan_wool",
	StackSize: 64,
}
var PurpleWool = &Item{
	ID: 92,
	Name: "purple_wool",
	StackSize: 64,
}
var BlueWool = &Item{
	ID: 93,
	Name: "blue_wool",
	StackSize: 64,
}
var BrownWool = &Item{
	ID: 94,
	Name: "brown_wool",
	StackSize: 64,
}
var GreenWool = &Item{
	ID: 95,
	Name: "green_wool",
	StackSize: 64,
}
var RedWool = &Item{
	ID: 96,
	Name: "red_wool",
	StackSize: 64,
}
var BlackWool = &Item{
	ID: 97,
	Name: "black_wool",
	StackSize: 64,
}
var Dandelion = &Item{
	ID: 98,
	Name: "dandelion",
	StackSize: 64,
}
var Poppy = &Item{
	ID: 99,
	Name: "poppy",
	StackSize: 64,
}
var BlueOrchid = &Item{
	ID: 100,
	Name: "blue_orchid",
	StackSize: 64,
}
var Allium = &Item{
	ID: 101,
	Name: "allium",
	StackSize: 64,
}
var AzureBluet = &Item{
	ID: 102,
	Name: "azure_bluet",
	StackSize: 64,
}
var RedTulip = &Item{
	ID: 103,
	Name: "red_tulip",
	StackSize: 64,
}
var OrangeTulip = &Item{
	ID: 104,
	Name: "orange_tulip",
	StackSize: 64,
}
var WhiteTulip = &Item{
	ID: 105,
	Name: "white_tulip",
	StackSize: 64,
}
var PinkTulip = &Item{
	ID: 106,
	Name: "pink_tulip",
	StackSize: 64,
}
var OxeyeDaisy = &Item{
	ID: 107,
	Name: "oxeye_daisy",
	StackSize: 64,
}
var Cornflower = &Item{
	ID: 108,
	Name: "cornflower",
	StackSize: 64,
}
var LilyOfTheValley = &Item{
	ID: 109,
	Name: "lily_of_the_valley",
	StackSize: 64,
}
var WitherRose = &Item{
	ID: 110,
	Name: "wither_rose",
	StackSize: 64,
}
var BrownMushroom = &Item{
	ID: 111,
	Name: "brown_mushroom",
	StackSize: 64,
}
var RedMushroom = &Item{
	ID: 112,
	Name: "red_mushroom",
	StackSize: 64,
}
var GoldBlock = &Item{
	ID: 113,
	Name: "gold_block",
	StackSize: 64,
}
var IronBlock = &Item{
	ID: 114,
	Name: "iron_block",
	StackSize: 64,
}
var OakSlab = &Item{
	ID: 115,
	Name: "oak_slab",
	StackSize: 64,
}
var SpruceSlab = &Item{
	ID: 116,
	Name: "spruce_slab",
	StackSize: 64,
}
var BirchSlab = &Item{
	ID: 117,
	Name: "birch_slab",
	StackSize: 64,
}
var JungleSlab = &Item{
	ID: 118,
	Name: "jungle_slab",
	StackSize: 64,
}
var AcaciaSlab = &Item{
	ID: 119,
	Name: "acacia_slab",
	StackSize: 64,
}
var DarkOakSlab = &Item{
	ID: 120,
	Name: "dark_oak_slab",
	StackSize: 64,
}
var StoneSlab = &Item{
	ID: 121,
	Name: "stone_slab",
	StackSize: 64,
}
var SmoothStoneSlab = &Item{
	ID: 122,
	Name: "smooth_stone_slab",
	StackSize: 64,
}
var SandstoneSlab = &Item{
	ID: 123,
	Name: "sandstone_slab",
	StackSize: 64,
}
var CutSandstoneSlab = &Item{
	ID: 124,
	Name: "cut_sandstone_slab",
	StackSize: 64,
}
var PetrifiedOakSlab = &Item{
	ID: 125,
	Name: "petrified_oak_slab",
	StackSize: 64,
}
var CobblestoneSlab = &Item{
	ID: 126,
	Name: "cobblestone_slab",
	StackSize: 64,
}
var BrickSlab = &Item{
	ID: 127,
	Name: "brick_slab",
	StackSize: 64,
}
var StoneBrickSlab = &Item{
	ID: 128,
	Name: "stone_brick_slab",
	StackSize: 64,
}
var NetherBrickSlab = &Item{
	ID: 129,
	Name: "nether_brick_slab",
	StackSize: 64,
}
var QuartzSlab = &Item{
	ID: 130,
	Name: "quartz_slab",
	StackSize: 64,
}
var RedSandstoneSlab = &Item{
	ID: 131,
	Name: "red_sandstone_slab",
	StackSize: 64,
}
var CutRedSandstoneSlab = &Item{
	ID: 132,
	Name: "cut_red_sandstone_slab",
	StackSize: 64,
}
var PurpurSlab = &Item{
	ID: 133,
	Name: "purpur_slab",
	StackSize: 64,
}
var PrismarineSlab = &Item{
	ID: 134,
	Name: "prismarine_slab",
	StackSize: 64,
}
var PrismarineBrickSlab = &Item{
	ID: 135,
	Name: "prismarine_brick_slab",
	StackSize: 64,
}
var DarkPrismarineSlab = &Item{
	ID: 136,
	Name: "dark_prismarine_slab",
	StackSize: 64,
}
var SmoothQuartz = &Item{
	ID: 137,
	Name: "smooth_quartz",
	StackSize: 64,
}
var SmoothRedSandstone = &Item{
	ID: 138,
	Name: "smooth_red_sandstone",
	StackSize: 64,
}
var SmoothSandstone = &Item{
	ID: 139,
	Name: "smooth_sandstone",
	StackSize: 64,
}
var SmoothStone = &Item{
	ID: 140,
	Name: "smooth_stone",
	StackSize: 64,
}
var Bricks = &Item{
	ID: 141,
	Name: "bricks",
	StackSize: 64,
}
var Tnt = &Item{
	ID: 142,
	Name: "tnt",
	StackSize: 64,
}
var Bookshelf = &Item{
	ID: 143,
	Name: "bookshelf",
	StackSize: 64,
}
var MossyCobblestone = &Item{
	ID: 144,
	Name: "mossy_cobblestone",
	StackSize: 64,
}
var Obsidian = &Item{
	ID: 145,
	Name: "obsidian",
	StackSize: 64,
}
var Torch = &Item{
	ID: 146,
	Name: "torch",
	StackSize: 64,
}
var EndRod = &Item{
	ID: 147,
	Name: "end_rod",
	StackSize: 64,
}
var ChorusPlant = &Item{
	ID: 148,
	Name: "chorus_plant",
	StackSize: 64,
}
var ChorusFlower = &Item{
	ID: 149,
	Name: "chorus_flower",
	StackSize: 64,
}
var PurpurBlock = &Item{
	ID: 150,
	Name: "purpur_block",
	StackSize: 64,
}
var PurpurPillar = &Item{
	ID: 151,
	Name: "purpur_pillar",
	StackSize: 64,
}
var PurpurStairs = &Item{
	ID: 152,
	Name: "purpur_stairs",
	StackSize: 64,
}
var Spawner = &Item{
	ID: 153,
	Name: "spawner",
	StackSize: 64,
}
var OakStairs = &Item{
	ID: 154,
	Name: "oak_stairs",
	StackSize: 64,
}
var Chest = &Item{
	ID: 155,
	Name: "chest",
	StackSize: 64,
}
var DiamondOre = &Item{
	ID: 156,
	Name: "diamond_ore",
	StackSize: 64,
}
var DiamondBlock = &Item{
	ID: 157,
	Name: "diamond_block",
	StackSize: 64,
}
var CraftingTable = &Item{
	ID: 158,
	Name: "crafting_table",
	StackSize: 64,
}
var Farmland = &Item{
	ID: 159,
	Name: "farmland",
	StackSize: 64,
}
var Furnace = &Item{
	ID: 160,
	Name: "furnace",
	StackSize: 64,
}
var Ladder = &Item{
	ID: 161,
	Name: "ladder",
	StackSize: 64,
}
var Rail = &Item{
	ID: 162,
	Name: "rail",
	StackSize: 64,
}
var CobblestoneStairs = &Item{
	ID: 163,
	Name: "cobblestone_stairs",
	StackSize: 64,
}
var Lever = &Item{
	ID: 164,
	Name: "lever",
	StackSize: 64,
}
var StonePressurePlate = &Item{
	ID: 165,
	Name: "stone_pressure_plate",
	StackSize: 64,
}
var OakPressurePlate = &Item{
	ID: 166,
	Name: "oak_pressure_plate",
	StackSize: 64,
}
var SprucePressurePlate = &Item{
	ID: 167,
	Name: "spruce_pressure_plate",
	StackSize: 64,
}
var BirchPressurePlate = &Item{
	ID: 168,
	Name: "birch_pressure_plate",
	StackSize: 64,
}
var JunglePressurePlate = &Item{
	ID: 169,
	Name: "jungle_pressure_plate",
	StackSize: 64,
}
var AcaciaPressurePlate = &Item{
	ID: 170,
	Name: "acacia_pressure_plate",
	StackSize: 64,
}
var DarkOakPressurePlate = &Item{
	ID: 171,
	Name: "dark_oak_pressure_plate",
	StackSize: 64,
}
var RedstoneOre = &Item{
	ID: 172,
	Name: "redstone_ore",
	StackSize: 64,
}
var RedstoneTorch = &Item{
	ID: 173,
	Name: "redstone_torch",
	StackSize: 64,
}
var StoneButton = &Item{
	ID: 174,
	Name: "stone_button",
	StackSize: 64,
}
var Snow = &Item{
	ID: 175,
	Name: "snow",
	StackSize: 64,
}
var Ice = &Item{
	ID: 176,
	Name: "ice",
	StackSize: 64,
}
var SnowBlock = &Item{
	ID: 177,
	Name: "snow_block",
	StackSize: 64,
}
var Cactus = &Item{
	ID: 178,
	Name: "cactus",
	StackSize: 64,
}
var Clay = &Item{
	ID: 179,
	Name: "clay",
	StackSize: 64,
}
var Jukebox = &Item{
	ID: 180,
	Name: "jukebox",
	StackSize: 64,
}
var OakFence = &Item{
	ID: 181,
	Name: "oak_fence",
	StackSize: 64,
}
var SpruceFence = &Item{
	ID: 182,
	Name: "spruce_fence",
	StackSize: 64,
}
var BirchFence = &Item{
	ID: 183,
	Name: "birch_fence",
	StackSize: 64,
}
var JungleFence = &Item{
	ID: 184,
	Name: "jungle_fence",
	StackSize: 64,
}
var AcaciaFence = &Item{
	ID: 185,
	Name: "acacia_fence",
	StackSize: 64,
}
var DarkOakFence = &Item{
	ID: 186,
	Name: "dark_oak_fence",
	StackSize: 64,
}
var Pumpkin = &Item{
	ID: 187,
	Name: "pumpkin",
	StackSize: 64,
}
var CarvedPumpkin = &Item{
	ID: 188,
	Name: "carved_pumpkin",
	StackSize: 64,
}
var Netherrack = &Item{
	ID: 189,
	Name: "netherrack",
	StackSize: 64,
}
var SoulSand = &Item{
	ID: 190,
	Name: "soul_sand",
	StackSize: 64,
}
var Glowstone = &Item{
	ID: 191,
	Name: "glowstone",
	StackSize: 64,
}
var JackOLantern = &Item{
	ID: 192,
	Name: "jack_o_lantern",
	StackSize: 64,
}
var OakTrapdoor = &Item{
	ID: 193,
	Name: "oak_trapdoor",
	StackSize: 64,
}
var SpruceTrapdoor = &Item{
	ID: 194,
	Name: "spruce_trapdoor",
	StackSize: 64,
}
var BirchTrapdoor = &Item{
	ID: 195,
	Name: "birch_trapdoor",
	StackSize: 64,
}
var JungleTrapdoor = &Item{
	ID: 196,
	Name: "jungle_trapdoor",
	StackSize: 64,
}
var AcaciaTrapdoor = &Item{
	ID: 197,
	Name: "acacia_trapdoor",
	StackSize: 64,
}
var DarkOakTrapdoor = &Item{
	ID: 198,
	Name: "dark_oak_trapdoor",
	StackSize: 64,
}
var InfestedStone = &Item{
	ID: 199,
	Name: "infested_stone",
	StackSize: 64,
}
var InfestedCobblestone = &Item{
	ID: 200,
	Name: "infested_cobblestone",
	StackSize: 64,
}
var InfestedStoneBricks = &Item{
	ID: 201,
	Name: "infested_stone_bricks",
	StackSize: 64,
}
var InfestedMossyStoneBricks = &Item{
	ID: 202,
	Name: "infested_mossy_stone_bricks",
	StackSize: 64,
}
var InfestedCrackedStoneBricks = &Item{
	ID: 203,
	Name: "infested_cracked_stone_bricks",
	StackSize: 64,
}
var InfestedChiseledStoneBricks = &Item{
	ID: 204,
	Name: "infested_chiseled_stone_bricks",
	StackSize: 64,
}
var StoneBricks = &Item{
	ID: 205,
	Name: "stone_bricks",
	StackSize: 64,
}
var MossyStoneBricks = &Item{
	ID: 206,
	Name: "mossy_stone_bricks",
	StackSize: 64,
}
var CrackedStoneBricks = &Item{
	ID: 207,
	Name: "cracked_stone_bricks",
	StackSize: 64,
}
var ChiseledStoneBricks = &Item{
	ID: 208,
	Name: "chiseled_stone_bricks",
	StackSize: 64,
}
var BrownMushroomBlock = &Item{
	ID: 209,
	Name: "brown_mushroom_block",
	StackSize: 64,
}
var RedMushroomBlock = &Item{
	ID: 210,
	Name: "red_mushroom_block",
	StackSize: 64,
}
var MushroomStem = &Item{
	ID: 211,
	Name: "mushroom_stem",
	StackSize: 64,
}
var IronBars = &Item{
	ID: 212,
	Name: "iron_bars",
	StackSize: 64,
}
var GlassPane = &Item{
	ID: 213,
	Name: "glass_pane",
	StackSize: 64,
}
var Melon = &Item{
	ID: 214,
	Name: "melon",
	StackSize: 64,
}
var Vine = &Item{
	ID: 215,
	Name: "vine",
	StackSize: 64,
}
var OakFenceGate = &Item{
	ID: 216,
	Name: "oak_fence_gate",
	StackSize: 64,
}
var SpruceFenceGate = &Item{
	ID: 217,
	Name: "spruce_fence_gate",
	StackSize: 64,
}
var BirchFenceGate = &Item{
	ID: 218,
	Name: "birch_fence_gate",
	StackSize: 64,
}
var JungleFenceGate = &Item{
	ID: 219,
	Name: "jungle_fence_gate",
	StackSize: 64,
}
var AcaciaFenceGate = &Item{
	ID: 220,
	Name: "acacia_fence_gate",
	StackSize: 64,
}
var DarkOakFenceGate = &Item{
	ID: 221,
	Name: "dark_oak_fence_gate",
	StackSize: 64,
}
var BrickStairs = &Item{
	ID: 222,
	Name: "brick_stairs",
	StackSize: 64,
}
var StoneBrickStairs = &Item{
	ID: 223,
	Name: "stone_brick_stairs",
	StackSize: 64,
}
var Mycelium = &Item{
	ID: 224,
	Name: "mycelium",
	StackSize: 64,
}
var LilyPad = &Item{
	ID: 225,
	Name: "lily_pad",
	StackSize: 64,
}
var NetherBricks = &Item{
	ID: 226,
	Name: "nether_bricks",
	StackSize: 64,
}
var NetherBrickFence = &Item{
	ID: 227,
	Name: "nether_brick_fence",
	StackSize: 64,
}
var NetherBrickStairs = &Item{
	ID: 228,
	Name: "nether_brick_stairs",
	StackSize: 64,
}
var EnchantingTable = &Item{
	ID: 229,
	Name: "enchanting_table",
	StackSize: 64,
}
var EndPortalFrame = &Item{
	ID: 230,
	Name: "end_portal_frame",
	StackSize: 64,
}
var EndStone = &Item{
	ID: 231,
	Name: "end_stone",
	StackSize: 64,
}
var EndStoneBricks = &Item{
	ID: 232,
	Name: "end_stone_bricks",
	StackSize: 64,
}
var DragonEgg = &Item{
	ID: 233,
	Name: "dragon_egg",
	StackSize: 64,
}
var RedstoneLamp = &Item{
	ID: 234,
	Name: "redstone_lamp",
	StackSize: 64,
}
var SandstoneStairs = &Item{
	ID: 235,
	Name: "sandstone_stairs",
	StackSize: 64,
}
var EmeraldOre = &Item{
	ID: 236,
	Name: "emerald_ore",
	StackSize: 64,
}
var EnderChest = &Item{
	ID: 237,
	Name: "ender_chest",
	StackSize: 64,
}
var TripwireHook = &Item{
	ID: 238,
	Name: "tripwire_hook",
	StackSize: 64,
}
var EmeraldBlock = &Item{
	ID: 239,
	Name: "emerald_block",
	StackSize: 64,
}
var SpruceStairs = &Item{
	ID: 240,
	Name: "spruce_stairs",
	StackSize: 64,
}
var BirchStairs = &Item{
	ID: 241,
	Name: "birch_stairs",
	StackSize: 64,
}
var JungleStairs = &Item{
	ID: 242,
	Name: "jungle_stairs",
	StackSize: 64,
}
var CommandBlock = &Item{
	ID: 243,
	Name: "command_block",
	StackSize: 64,
}
var Beacon = &Item{
	ID: 244,
	Name: "beacon",
	StackSize: 64,
}
var CobblestoneWall = &Item{
	ID: 245,
	Name: "cobblestone_wall",
	StackSize: 64,
}
var MossyCobblestoneWall = &Item{
	ID: 246,
	Name: "mossy_cobblestone_wall",
	StackSize: 64,
}
var BrickWall = &Item{
	ID: 247,
	Name: "brick_wall",
	StackSize: 64,
}
var PrismarineWall = &Item{
	ID: 248,
	Name: "prismarine_wall",
	StackSize: 64,
}
var RedSandstoneWall = &Item{
	ID: 249,
	Name: "red_sandstone_wall",
	StackSize: 64,
}
var MossyStoneBrickWall = &Item{
	ID: 250,
	Name: "mossy_stone_brick_wall",
	StackSize: 64,
}
var GraniteWall = &Item{
	ID: 251,
	Name: "granite_wall",
	StackSize: 64,
}
var StoneBrickWall = &Item{
	ID: 252,
	Name: "stone_brick_wall",
	StackSize: 64,
}
var NetherBrickWall = &Item{
	ID: 253,
	Name: "nether_brick_wall",
	StackSize: 64,
}
var AndesiteWall = &Item{
	ID: 254,
	Name: "andesite_wall",
	StackSize: 64,
}
var RedNetherBrickWall = &Item{
	ID: 255,
	Name: "red_nether_brick_wall",
	StackSize: 64,
}
var SandstoneWall = &Item{
	ID: 256,
	Name: "sandstone_wall",
	StackSize: 64,
}
var EndStoneBrickWall = &Item{
	ID: 257,
	Name: "end_stone_brick_wall",
	StackSize: 64,
}
var DioriteWall = &Item{
	ID: 258,
	Name: "diorite_wall",
	StackSize: 64,
}
var OakButton = &Item{
	ID: 259,
	Name: "oak_button",
	StackSize: 64,
}
var SpruceButton = &Item{
	ID: 260,
	Name: "spruce_button",
	StackSize: 64,
}
var BirchButton = &Item{
	ID: 261,
	Name: "birch_button",
	StackSize: 64,
}
var JungleButton = &Item{
	ID: 262,
	Name: "jungle_button",
	StackSize: 64,
}
var AcaciaButton = &Item{
	ID: 263,
	Name: "acacia_button",
	StackSize: 64,
}
var DarkOakButton = &Item{
	ID: 264,
	Name: "dark_oak_button",
	StackSize: 64,
}
var Anvil = &Item{
	ID: 265,
	Name: "anvil",
	StackSize: 64,
}
var ChippedAnvil = &Item{
	ID: 266,
	Name: "chipped_anvil",
	StackSize: 64,
}
var DamagedAnvil = &Item{
	ID: 267,
	Name: "damaged_anvil",
	StackSize: 64,
}
var TrappedChest = &Item{
	ID: 268,
	Name: "trapped_chest",
	StackSize: 64,
}
var LightWeightedPressurePlate = &Item{
	ID: 269,
	Name: "light_weighted_pressure_plate",
	StackSize: 64,
}
var HeavyWeightedPressurePlate = &Item{
	ID: 270,
	Name: "heavy_weighted_pressure_plate",
	StackSize: 64,
}
var DaylightDetector = &Item{
	ID: 271,
	Name: "daylight_detector",
	StackSize: 64,
}
var RedstoneBlock = &Item{
	ID: 272,
	Name: "redstone_block",
	StackSize: 64,
}
var NetherQuartzOre = &Item{
	ID: 273,
	Name: "nether_quartz_ore",
	StackSize: 64,
}
var Hopper = &Item{
	ID: 274,
	Name: "hopper",
	StackSize: 64,
}
var ChiseledQuartzBlock = &Item{
	ID: 275,
	Name: "chiseled_quartz_block",
	StackSize: 64,
}
var QuartzBlock = &Item{
	ID: 276,
	Name: "quartz_block",
	StackSize: 64,
}
var QuartzPillar = &Item{
	ID: 277,
	Name: "quartz_pillar",
	StackSize: 64,
}
var QuartzStairs = &Item{
	ID: 278,
	Name: "quartz_stairs",
	StackSize: 64,
}
var ActivatorRail = &Item{
	ID: 279,
	Name: "activator_rail",
	StackSize: 64,
}
var Dropper = &Item{
	ID: 280,
	Name: "dropper",
	StackSize: 64,
}
var WhiteTerracotta = &Item{
	ID: 281,
	Name: "white_terracotta",
	StackSize: 64,
}
var OrangeTerracotta = &Item{
	ID: 282,
	Name: "orange_terracotta",
	StackSize: 64,
}
var MagentaTerracotta = &Item{
	ID: 283,
	Name: "magenta_terracotta",
	StackSize: 64,
}
var LightBlueTerracotta = &Item{
	ID: 284,
	Name: "light_blue_terracotta",
	StackSize: 64,
}
var YellowTerracotta = &Item{
	ID: 285,
	Name: "yellow_terracotta",
	StackSize: 64,
}
var LimeTerracotta = &Item{
	ID: 286,
	Name: "lime_terracotta",
	StackSize: 64,
}
var PinkTerracotta = &Item{
	ID: 287,
	Name: "pink_terracotta",
	StackSize: 64,
}
var GrayTerracotta = &Item{
	ID: 288,
	Name: "gray_terracotta",
	StackSize: 64,
}
var LightGrayTerracotta = &Item{
	ID: 289,
	Name: "light_gray_terracotta",
	StackSize: 64,
}
var CyanTerracotta = &Item{
	ID: 290,
	Name: "cyan_terracotta",
	StackSize: 64,
}
var PurpleTerracotta = &Item{
	ID: 291,
	Name: "purple_terracotta",
	StackSize: 64,
}
var BlueTerracotta = &Item{
	ID: 292,
	Name: "blue_terracotta",
	StackSize: 64,
}
var BrownTerracotta = &Item{
	ID: 293,
	Name: "brown_terracotta",
	StackSize: 64,
}
var GreenTerracotta = &Item{
	ID: 294,
	Name: "green_terracotta",
	StackSize: 64,
}
var RedTerracotta = &Item{
	ID: 295,
	Name: "red_terracotta",
	StackSize: 64,
}
var BlackTerracotta = &Item{
	ID: 296,
	Name: "black_terracotta",
	StackSize: 64,
}
var Barrier = &Item{
	ID: 297,
	Name: "barrier",
	StackSize: 64,
}
var IronTrapdoor = &Item{
	ID: 298,
	Name: "iron_trapdoor",
	StackSize: 64,
}
var HayBlock = &Item{
	ID: 299,
	Name: "hay_block",
	StackSize: 64,
}
var WhiteCarpet = &Item{
	ID: 300,
	Name: "white_carpet",
	StackSize: 64,
}
var OrangeCarpet = &Item{
	ID: 301,
	Name: "orange_carpet",
	StackSize: 64,
}
var MagentaCarpet = &Item{
	ID: 302,
	Name: "magenta_carpet",
	StackSize: 64,
}
var LightBlueCarpet = &Item{
	ID: 303,
	Name: "light_blue_carpet",
	StackSize: 64,
}
var YellowCarpet = &Item{
	ID: 304,
	Name: "yellow_carpet",
	StackSize: 64,
}
var LimeCarpet = &Item{
	ID: 305,
	Name: "lime_carpet",
	StackSize: 64,
}
var PinkCarpet = &Item{
	ID: 306,
	Name: "pink_carpet",
	StackSize: 64,
}
var GrayCarpet = &Item{
	ID: 307,
	Name: "gray_carpet",
	StackSize: 64,
}
var LightGrayCarpet = &Item{
	ID: 308,
	Name: "light_gray_carpet",
	StackSize: 64,
}
var CyanCarpet = &Item{
	ID: 309,
	Name: "cyan_carpet",
	StackSize: 64,
}
var PurpleCarpet = &Item{
	ID: 310,
	Name: "purple_carpet",
	StackSize: 64,
}
var BlueCarpet = &Item{
	ID: 311,
	Name: "blue_carpet",
	StackSize: 64,
}
var BrownCarpet = &Item{
	ID: 312,
	Name: "brown_carpet",
	StackSize: 64,
}
var GreenCarpet = &Item{
	ID: 313,
	Name: "green_carpet",
	StackSize: 64,
}
var RedCarpet = &Item{
	ID: 314,
	Name: "red_carpet",
	StackSize: 64,
}
var BlackCarpet = &Item{
	ID: 315,
	Name: "black_carpet",
	StackSize: 64,
}
var Terracotta = &Item{
	ID: 316,
	Name: "terracotta",
	StackSize: 64,
}
var CoalBlock = &Item{
	ID: 317,
	Name: "coal_block",
	StackSize: 64,
}
var PackedIce = &Item{
	ID: 318,
	Name: "packed_ice",
	StackSize: 64,
}
var AcaciaStairs = &Item{
	ID: 319,
	Name: "acacia_stairs",
	StackSize: 64,
}
var DarkOakStairs = &Item{
	ID: 320,
	Name: "dark_oak_stairs",
	StackSize: 64,
}
var SlimeBlock = &Item{
	ID: 321,
	Name: "slime_block",
	StackSize: 64,
}
var GrassPath = &Item{
	ID: 322,
	Name: "grass_path",
	StackSize: 64,
}
var Sunflower = &Item{
	ID: 323,
	Name: "sunflower",
	StackSize: 64,
}
var Lilac = &Item{
	ID: 324,
	Name: "lilac",
	StackSize: 64,
}
var RoseBush = &Item{
	ID: 325,
	Name: "rose_bush",
	StackSize: 64,
}
var Peony = &Item{
	ID: 326,
	Name: "peony",
	StackSize: 64,
}
var TallGrass = &Item{
	ID: 327,
	Name: "tall_grass",
	StackSize: 64,
}
var LargeFern = &Item{
	ID: 328,
	Name: "large_fern",
	StackSize: 64,
}
var WhiteStainedGlass = &Item{
	ID: 329,
	Name: "white_stained_glass",
	StackSize: 64,
}
var OrangeStainedGlass = &Item{
	ID: 330,
	Name: "orange_stained_glass",
	StackSize: 64,
}
var MagentaStainedGlass = &Item{
	ID: 331,
	Name: "magenta_stained_glass",
	StackSize: 64,
}
var LightBlueStainedGlass = &Item{
	ID: 332,
	Name: "light_blue_stained_glass",
	StackSize: 64,
}
var YellowStainedGlass = &Item{
	ID: 333,
	Name: "yellow_stained_glass",
	StackSize: 64,
}
var LimeStainedGlass = &Item{
	ID: 334,
	Name: "lime_stained_glass",
	StackSize: 64,
}
var PinkStainedGlass = &Item{
	ID: 335,
	Name: "pink_stained_glass",
	StackSize: 64,
}
var GrayStainedGlass = &Item{
	ID: 336,
	Name: "gray_stained_glass",
	StackSize: 64,
}
var LightGrayStainedGlass = &Item{
	ID: 337,
	Name: "light_gray_stained_glass",
	StackSize: 64,
}
var CyanStainedGlass = &Item{
	ID: 338,
	Name: "cyan_stained_glass",
	StackSize: 64,
}
var PurpleStainedGlass = &Item{
	ID: 339,
	Name: "purple_stained_glass",
	StackSize: 64,
}
var BlueStainedGlass = &Item{
	ID: 340,
	Name: "blue_stained_glass",
	StackSize: 64,
}
var BrownStainedGlass = &Item{
	ID: 341,
	Name: "brown_stained_glass",
	StackSize: 64,
}
var GreenStainedGlass = &Item{
	ID: 342,
	Name: "green_stained_glass",
	StackSize: 64,
}
var RedStainedGlass = &Item{
	ID: 343,
	Name: "red_stained_glass",
	StackSize: 64,
}
var BlackStainedGlass = &Item{
	ID: 344,
	Name: "black_stained_glass",
	StackSize: 64,
}
var WhiteStainedGlassPane = &Item{
	ID: 345,
	Name: "white_stained_glass_pane",
	StackSize: 64,
}
var OrangeStainedGlassPane = &Item{
	ID: 346,
	Name: "orange_stained_glass_pane",
	StackSize: 64,
}
var MagentaStainedGlassPane = &Item{
	ID: 347,
	Name: "magenta_stained_glass_pane",
	StackSize: 64,
}
var LightBlueStainedGlassPane = &Item{
	ID: 348,
	Name: "light_blue_stained_glass_pane",
	StackSize: 64,
}
var YellowStainedGlassPane = &Item{
	ID: 349,
	Name: "yellow_stained_glass_pane",
	StackSize: 64,
}
var LimeStainedGlassPane = &Item{
	ID: 350,
	Name: "lime_stained_glass_pane",
	StackSize: 64,
}
var PinkStainedGlassPane = &Item{
	ID: 351,
	Name: "pink_stained_glass_pane",
	StackSize: 64,
}
var GrayStainedGlassPane = &Item{
	ID: 352,
	Name: "gray_stained_glass_pane",
	StackSize: 64,
}
var LightGrayStainedGlassPane = &Item{
	ID: 353,
	Name: "light_gray_stained_glass_pane",
	StackSize: 64,
}
var CyanStainedGlassPane = &Item{
	ID: 354,
	Name: "cyan_stained_glass_pane",
	StackSize: 64,
}
var PurpleStainedGlassPane = &Item{
	ID: 355,
	Name: "purple_stained_glass_pane",
	StackSize: 64,
}
var BlueStainedGlassPane = &Item{
	ID: 356,
	Name: "blue_stained_glass_pane",
	StackSize: 64,
}
var BrownStainedGlassPane = &Item{
	ID: 357,
	Name: "brown_stained_glass_pane",
	StackSize: 64,
}
var GreenStainedGlassPane = &Item{
	ID: 358,
	Name: "green_stained_glass_pane",
	StackSize: 64,
}
var RedStainedGlassPane = &Item{
	ID: 359,
	Name: "red_stained_glass_pane",
	StackSize: 64,
}
var BlackStainedGlassPane = &Item{
	ID: 360,
	Name: "black_stained_glass_pane",
	StackSize: 64,
}
var Prismarine = &Item{
	ID: 361,
	Name: "prismarine",
	StackSize: 64,
}
var PrismarineBricks = &Item{
	ID: 362,
	Name: "prismarine_bricks",
	StackSize: 64,
}
var DarkPrismarine = &Item{
	ID: 363,
	Name: "dark_prismarine",
	StackSize: 64,
}
var PrismarineStairs = &Item{
	ID: 364,
	Name: "prismarine_stairs",
	StackSize: 64,
}
var PrismarineBrickStairs = &Item{
	ID: 365,
	Name: "prismarine_brick_stairs",
	StackSize: 64,
}
var DarkPrismarineStairs = &Item{
	ID: 366,
	Name: "dark_prismarine_stairs",
	StackSize: 64,
}
var SeaLantern = &Item{
	ID: 367,
	Name: "sea_lantern",
	StackSize: 64,
}
var RedSandstone = &Item{
	ID: 368,
	Name: "red_sandstone",
	StackSize: 64,
}
var ChiseledRedSandstone = &Item{
	ID: 369,
	Name: "chiseled_red_sandstone",
	StackSize: 64,
}
var CutRedSandstone = &Item{
	ID: 370,
	Name: "cut_red_sandstone",
	StackSize: 64,
}
var RedSandstoneStairs = &Item{
	ID: 371,
	Name: "red_sandstone_stairs",
	StackSize: 64,
}
var RepeatingCommandBlock = &Item{
	ID: 372,
	Name: "repeating_command_block",
	StackSize: 64,
}
var ChainCommandBlock = &Item{
	ID: 373,
	Name: "chain_command_block",
	StackSize: 64,
}
var MagmaBlock = &Item{
	ID: 374,
	Name: "magma_block",
	StackSize: 64,
}
var NetherWartBlock = &Item{
	ID: 375,
	Name: "nether_wart_block",
	StackSize: 64,
}
var RedNetherBricks = &Item{
	ID: 376,
	Name: "red_nether_bricks",
	StackSize: 64,
}
var BoneBlock = &Item{
	ID: 377,
	Name: "bone_block",
	StackSize: 64,
}
var StructureVoid = &Item{
	ID: 378,
	Name: "structure_void",
	StackSize: 64,
}
var Observer = &Item{
	ID: 379,
	Name: "observer",
	StackSize: 64,
}
var ShulkerBox = &Item{
	ID: 380,
	Name: "shulker_box",
	StackSize: 1,
}
var WhiteShulkerBox = &Item{
	ID: 381,
	Name: "white_shulker_box",
	StackSize: 1,
}
var OrangeShulkerBox = &Item{
	ID: 382,
	Name: "orange_shulker_box",
	StackSize: 1,
}
var MagentaShulkerBox = &Item{
	ID: 383,
	Name: "magenta_shulker_box",
	StackSize: 1,
}
var LightBlueShulkerBox = &Item{
	ID: 384,
	Name: "light_blue_shulker_box",
	StackSize: 1,
}
var YellowShulkerBox = &Item{
	ID: 385,
	Name: "yellow_shulker_box",
	StackSize: 1,
}
var LimeShulkerBox = &Item{
	ID: 386,
	Name: "lime_shulker_box",
	StackSize: 1,
}
var PinkShulkerBox = &Item{
	ID: 387,
	Name: "pink_shulker_box",
	StackSize: 1,
}
var GrayShulkerBox = &Item{
	ID: 388,
	Name: "gray_shulker_box",
	StackSize: 1,
}
var LightGrayShulkerBox = &Item{
	ID: 389,
	Name: "light_gray_shulker_box",
	StackSize: 1,
}
var CyanShulkerBox = &Item{
	ID: 390,
	Name: "cyan_shulker_box",
	StackSize: 1,
}
var PurpleShulkerBox = &Item{
	ID: 391,
	Name: "purple_shulker_box",
	StackSize: 1,
}
var BlueShulkerBox = &Item{
	ID: 392,
	Name: "blue_shulker_box",
	StackSize: 1,
}
var BrownShulkerBox = &Item{
	ID: 393,
	Name: "brown_shulker_box",
	StackSize: 1,
}
var GreenShulkerBox = &Item{
	ID: 394,
	Name: "green_shulker_box",
	StackSize: 1,
}
var RedShulkerBox = &Item{
	ID: 395,
	Name: "red_shulker_box",
	StackSize: 1,
}
var BlackShulkerBox = &Item{
	ID: 396,
	Name: "black_shulker_box",
	StackSize: 1,
}
var WhiteGlazedTerracotta = &Item{
	ID: 397,
	Name: "white_glazed_terracotta",
	StackSize: 64,
}
var OrangeGlazedTerracotta = &Item{
	ID: 398,
	Name: "orange_glazed_terracotta",
	StackSize: 64,
}
var MagentaGlazedTerracotta = &Item{
	ID: 399,
	Name: "magenta_glazed_terracotta",
	StackSize: 64,
}
var LightBlueGlazedTerracotta = &Item{
	ID: 400,
	Name: "light_blue_glazed_terracotta",
	StackSize: 64,
}
var YellowGlazedTerracotta = &Item{
	ID: 401,
	Name: "yellow_glazed_terracotta",
	StackSize: 64,
}
var LimeGlazedTerracotta = &Item{
	ID: 402,
	Name: "lime_glazed_terracotta",
	StackSize: 64,
}
var PinkGlazedTerracotta = &Item{
	ID: 403,
	Name: "pink_glazed_terracotta",
	StackSize: 64,
}
var GrayGlazedTerracotta = &Item{
	ID: 404,
	Name: "gray_glazed_terracotta",
	StackSize: 64,
}
var LightGrayGlazedTerracotta = &Item{
	ID: 405,
	Name: "light_gray_glazed_terracotta",
	StackSize: 64,
}
var CyanGlazedTerracotta = &Item{
	ID: 406,
	Name: "cyan_glazed_terracotta",
	StackSize: 64,
}
var PurpleGlazedTerracotta = &Item{
	ID: 407,
	Name: "purple_glazed_terracotta",
	StackSize: 64,
}
var BlueGlazedTerracotta = &Item{
	ID: 408,
	Name: "blue_glazed_terracotta",
	StackSize: 64,
}
var BrownGlazedTerracotta = &Item{
	ID: 409,
	Name: "brown_glazed_terracotta",
	StackSize: 64,
}
var GreenGlazedTerracotta = &Item{
	ID: 410,
	Name: "green_glazed_terracotta",
	StackSize: 64,
}
var RedGlazedTerracotta = &Item{
	ID: 411,
	Name: "red_glazed_terracotta",
	StackSize: 64,
}
var BlackGlazedTerracotta = &Item{
	ID: 412,
	Name: "black_glazed_terracotta",
	StackSize: 64,
}
var WhiteConcrete = &Item{
	ID: 413,
	Name: "white_concrete",
	StackSize: 64,
}
var OrangeConcrete = &Item{
	ID: 414,
	Name: "orange_concrete",
	StackSize: 64,
}
var MagentaConcrete = &Item{
	ID: 415,
	Name: "magenta_concrete",
	StackSize: 64,
}
var LightBlueConcrete = &Item{
	ID: 416,
	Name: "light_blue_concrete",
	StackSize: 64,
}
var YellowConcrete = &Item{
	ID: 417,
	Name: "yellow_concrete",
	StackSize: 64,
}
var LimeConcrete = &Item{
	ID: 418,
	Name: "lime_concrete",
	StackSize: 64,
}
var PinkConcrete = &Item{
	ID: 419,
	Name: "pink_concrete",
	StackSize: 64,
}
var GrayConcrete = &Item{
	ID: 420,
	Name: "gray_concrete",
	StackSize: 64,
}
var LightGrayConcrete = &Item{
	ID: 421,
	Name: "light_gray_concrete",
	StackSize: 64,
}
var CyanConcrete = &Item{
	ID: 422,
	Name: "cyan_concrete",
	StackSize: 64,
}
var PurpleConcrete = &Item{
	ID: 423,
	Name: "purple_concrete",
	StackSize: 64,
}
var BlueConcrete = &Item{
	ID: 424,
	Name: "blue_concrete",
	StackSize: 64,
}
var BrownConcrete = &Item{
	ID: 425,
	Name: "brown_concrete",
	StackSize: 64,
}
var GreenConcrete = &Item{
	ID: 426,
	Name: "green_concrete",
	StackSize: 64,
}
var RedConcrete = &Item{
	ID: 427,
	Name: "red_concrete",
	StackSize: 64,
}
var BlackConcrete = &Item{
	ID: 428,
	Name: "black_concrete",
	StackSize: 64,
}
var WhiteConcretePowder = &Item{
	ID: 429,
	Name: "white_concrete_powder",
	StackSize: 64,
}
var OrangeConcretePowder = &Item{
	ID: 430,
	Name: "orange_concrete_powder",
	StackSize: 64,
}
var MagentaConcretePowder = &Item{
	ID: 431,
	Name: "magenta_concrete_powder",
	StackSize: 64,
}
var LightBlueConcretePowder = &Item{
	ID: 432,
	Name: "light_blue_concrete_powder",
	StackSize: 64,
}
var YellowConcretePowder = &Item{
	ID: 433,
	Name: "yellow_concrete_powder",
	StackSize: 64,
}
var LimeConcretePowder = &Item{
	ID: 434,
	Name: "lime_concrete_powder",
	StackSize: 64,
}
var PinkConcretePowder = &Item{
	ID: 435,
	Name: "pink_concrete_powder",
	StackSize: 64,
}
var GrayConcretePowder = &Item{
	ID: 436,
	Name: "gray_concrete_powder",
	StackSize: 64,
}
var LightGrayConcretePowder = &Item{
	ID: 437,
	Name: "light_gray_concrete_powder",
	StackSize: 64,
}
var CyanConcretePowder = &Item{
	ID: 438,
	Name: "cyan_concrete_powder",
	StackSize: 64,
}
var PurpleConcretePowder = &Item{
	ID: 439,
	Name: "purple_concrete_powder",
	StackSize: 64,
}
var BlueConcretePowder = &Item{
	ID: 440,
	Name: "blue_concrete_powder",
	StackSize: 64,
}
var BrownConcretePowder = &Item{
	ID: 441,
	Name: "brown_concrete_powder",
	StackSize: 64,
}
var GreenConcretePowder = &Item{
	ID: 442,
	Name: "green_concrete_powder",
	StackSize: 64,
}
var RedConcretePowder = &Item{
	ID: 443,
	Name: "red_concrete_powder",
	StackSize: 64,
}
var BlackConcretePowder = &Item{
	ID: 444,
	Name: "black_concrete_powder",
	StackSize: 64,
}
var TurtleEgg = &Item{
	ID: 445,
	Name: "turtle_egg",
	StackSize: 64,
}
var DeadTubeCoralBlock = &Item{
	ID: 446,
	Name: "dead_tube_coral_block",
	StackSize: 64,
}
var DeadBrainCoralBlock = &Item{
	ID: 447,
	Name: "dead_brain_coral_block",
	StackSize: 64,
}
var DeadBubbleCoralBlock = &Item{
	ID: 448,
	Name: "dead_bubble_coral_block",
	StackSize: 64,
}
var DeadFireCoralBlock = &Item{
	ID: 449,
	Name: "dead_fire_coral_block",
	StackSize: 64,
}
var DeadHornCoralBlock = &Item{
	ID: 450,
	Name: "dead_horn_coral_block",
	StackSize: 64,
}
var TubeCoralBlock = &Item{
	ID: 451,
	Name: "tube_coral_block",
	StackSize: 64,
}
var BrainCoralBlock = &Item{
	ID: 452,
	Name: "brain_coral_block",
	StackSize: 64,
}
var BubbleCoralBlock = &Item{
	ID: 453,
	Name: "bubble_coral_block",
	StackSize: 64,
}
var FireCoralBlock = &Item{
	ID: 454,
	Name: "fire_coral_block",
	StackSize: 64,
}
var HornCoralBlock = &Item{
	ID: 455,
	Name: "horn_coral_block",
	StackSize: 64,
}
var TubeCoral = &Item{
	ID: 456,
	Name: "tube_coral",
	StackSize: 64,
}
var BrainCoral = &Item{
	ID: 457,
	Name: "brain_coral",
	StackSize: 64,
}
var BubbleCoral = &Item{
	ID: 458,
	Name: "bubble_coral",
	StackSize: 64,
}
var FireCoral = &Item{
	ID: 459,
	Name: "fire_coral",
	StackSize: 64,
}
var HornCoral = &Item{
	ID: 460,
	Name: "horn_coral",
	StackSize: 64,
}
var DeadBrainCoral = &Item{
	ID: 461,
	Name: "dead_brain_coral",
	StackSize: 64,
}
var DeadBubbleCoral = &Item{
	ID: 462,
	Name: "dead_bubble_coral",
	StackSize: 64,
}
var DeadFireCoral = &Item{
	ID: 463,
	Name: "dead_fire_coral",
	StackSize: 64,
}
var DeadHornCoral = &Item{
	ID: 464,
	Name: "dead_horn_coral",
	StackSize: 64,
}
var DeadTubeCoral = &Item{
	ID: 465,
	Name: "dead_tube_coral",
	StackSize: 64,
}
var TubeCoralFan = &Item{
	ID: 466,
	Name: "tube_coral_fan",
	StackSize: 64,
}
var BrainCoralFan = &Item{
	ID: 467,
	Name: "brain_coral_fan",
	StackSize: 64,
}
var BubbleCoralFan = &Item{
	ID: 468,
	Name: "bubble_coral_fan",
	StackSize: 64,
}
var FireCoralFan = &Item{
	ID: 469,
	Name: "fire_coral_fan",
	StackSize: 64,
}
var HornCoralFan = &Item{
	ID: 470,
	Name: "horn_coral_fan",
	StackSize: 64,
}
var DeadTubeCoralFan = &Item{
	ID: 471,
	Name: "dead_tube_coral_fan",
	StackSize: 64,
}
var DeadBrainCoralFan = &Item{
	ID: 472,
	Name: "dead_brain_coral_fan",
	StackSize: 64,
}
var DeadBubbleCoralFan = &Item{
	ID: 473,
	Name: "dead_bubble_coral_fan",
	StackSize: 64,
}
var DeadFireCoralFan = &Item{
	ID: 474,
	Name: "dead_fire_coral_fan",
	StackSize: 64,
}
var DeadHornCoralFan = &Item{
	ID: 475,
	Name: "dead_horn_coral_fan",
	StackSize: 64,
}
var BlueIce = &Item{
	ID: 476,
	Name: "blue_ice",
	StackSize: 64,
}
var Conduit = &Item{
	ID: 477,
	Name: "conduit",
	StackSize: 64,
}
var PolishedGraniteStairs = &Item{
	ID: 478,
	Name: "polished_granite_stairs",
	StackSize: 64,
}
var SmoothRedSandstoneStairs = &Item{
	ID: 479,
	Name: "smooth_red_sandstone_stairs",
	StackSize: 64,
}
var MossyStoneBrickStairs = &Item{
	ID: 480,
	Name: "mossy_stone_brick_stairs",
	StackSize: 64,
}
var PolishedDioriteStairs = &Item{
	ID: 481,
	Name: "polished_diorite_stairs",
	StackSize: 64,
}
var MossyCobblestoneStairs = &Item{
	ID: 482,
	Name: "mossy_cobblestone_stairs",
	StackSize: 64,
}
var EndStoneBrickStairs = &Item{
	ID: 483,
	Name: "end_stone_brick_stairs",
	StackSize: 64,
}
var StoneStairs = &Item{
	ID: 484,
	Name: "stone_stairs",
	StackSize: 64,
}
var SmoothSandstoneStairs = &Item{
	ID: 485,
	Name: "smooth_sandstone_stairs",
	StackSize: 64,
}
var SmoothQuartzStairs = &Item{
	ID: 486,
	Name: "smooth_quartz_stairs",
	StackSize: 64,
}
var GraniteStairs = &Item{
	ID: 487,
	Name: "granite_stairs",
	StackSize: 64,
}
var AndesiteStairs = &Item{
	ID: 488,
	Name: "andesite_stairs",
	StackSize: 64,
}
var RedNetherBrickStairs = &Item{
	ID: 489,
	Name: "red_nether_brick_stairs",
	StackSize: 64,
}
var PolishedAndesiteStairs = &Item{
	ID: 490,
	Name: "polished_andesite_stairs",
	StackSize: 64,
}
var DioriteStairs = &Item{
	ID: 491,
	Name: "diorite_stairs",
	StackSize: 64,
}
var PolishedGraniteSlab = &Item{
	ID: 492,
	Name: "polished_granite_slab",
	StackSize: 64,
}
var SmoothRedSandstoneSlab = &Item{
	ID: 493,
	Name: "smooth_red_sandstone_slab",
	StackSize: 64,
}
var MossyStoneBrickSlab = &Item{
	ID: 494,
	Name: "mossy_stone_brick_slab",
	StackSize: 64,
}
var PolishedDioriteSlab = &Item{
	ID: 495,
	Name: "polished_diorite_slab",
	StackSize: 64,
}
var MossyCobblestoneSlab = &Item{
	ID: 496,
	Name: "mossy_cobblestone_slab",
	StackSize: 64,
}
var EndStoneBrickSlab = &Item{
	ID: 497,
	Name: "end_stone_brick_slab",
	StackSize: 64,
}
var SmoothSandstoneSlab = &Item{
	ID: 498,
	Name: "smooth_sandstone_slab",
	StackSize: 64,
}
var SmoothQuartzSlab = &Item{
	ID: 499,
	Name: "smooth_quartz_slab",
	StackSize: 64,
}
var GraniteSlab = &Item{
	ID: 500,
	Name: "granite_slab",
	StackSize: 64,
}
var AndesiteSlab = &Item{
	ID: 501,
	Name: "andesite_slab",
	StackSize: 64,
}
var RedNetherBrickSlab = &Item{
	ID: 502,
	Name: "red_nether_brick_slab",
	StackSize: 64,
}
var PolishedAndesiteSlab = &Item{
	ID: 503,
	Name: "polished_andesite_slab",
	StackSize: 64,
}
var DioriteSlab = &Item{
	ID: 504,
	Name: "diorite_slab",
	StackSize: 64,
}
var Scaffolding = &Item{
	ID: 505,
	Name: "scaffolding",
	StackSize: 64,
}
var IronDoor = &Item{
	ID: 506,
	Name: "iron_door",
	StackSize: 64,
}
var OakDoor = &Item{
	ID: 507,
	Name: "oak_door",
	StackSize: 64,
}
var SpruceDoor = &Item{
	ID: 508,
	Name: "spruce_door",
	StackSize: 64,
}
var BirchDoor = &Item{
	ID: 509,
	Name: "birch_door",
	StackSize: 64,
}
var JungleDoor = &Item{
	ID: 510,
	Name: "jungle_door",
	StackSize: 64,
}
var AcaciaDoor = &Item{
	ID: 511,
	Name: "acacia_door",
	StackSize: 64,
}
var DarkOakDoor = &Item{
	ID: 512,
	Name: "dark_oak_door",
	StackSize: 64,
}
var Repeater = &Item{
	ID: 513,
	Name: "repeater",
	StackSize: 64,
}
var Comparator = &Item{
	ID: 514,
	Name: "comparator",
	StackSize: 64,
}
var StructureBlock = &Item{
	ID: 515,
	Name: "structure_block",
	StackSize: 64,
}
var Jigsaw = &Item{
	ID: 516,
	Name: "jigsaw",
	StackSize: 64,
}
var Composter = &Item{
	ID: 517,
	Name: "composter",
	StackSize: 64,
}
var TurtleHelmet = &Item{
	ID: 518,
	Name: "turtle_helmet",
	StackSize: 1,
}
var Scute = &Item{
	ID: 519,
	Name: "scute",
	StackSize: 64,
}
var IronShovel = &Item{
	ID: 520,
	Name: "iron_shovel",
	StackSize: 1,
}
var IronPickaxe = &Item{
	ID: 521,
	Name: "iron_pickaxe",
	StackSize: 1,
}
var IronAxe = &Item{
	ID: 522,
	Name: "iron_axe",
	StackSize: 1,
}
var FlintAndSteel = &Item{
	ID: 523,
	Name: "flint_and_steel",
	StackSize: 1,
}
var Apple = &Item{
	ID: 524,
	Name: "apple",
	StackSize: 64,
}
var Bow = &Item{
	ID: 525,
	Name: "bow",
	StackSize: 1,
}
var Arrow = &Item{
	ID: 526,
	Name: "arrow",
	StackSize: 64,
}
var Coal = &Item{
	ID: 527,
	Name: "coal",
	StackSize: 64,
}
var Charcoal = &Item{
	ID: 528,
	Name: "charcoal",
	StackSize: 64,
}
var Diamond = &Item{
	ID: 529,
	Name: "diamond",
	StackSize: 64,
}
var IronIngot = &Item{
	ID: 530,
	Name: "iron_ingot",
	StackSize: 64,
}
var GoldIngot = &Item{
	ID: 531,
	Name: "gold_ingot",
	StackSize: 64,
}
var IronSword = &Item{
	ID: 532,
	Name: "iron_sword",
	StackSize: 1,
}
var WoodenSword = &Item{
	ID: 533,
	Name: "wooden_sword",
	StackSize: 1,
}
var WoodenShovel = &Item{
	ID: 534,
	Name: "wooden_shovel",
	StackSize: 1,
}
var WoodenPickaxe = &Item{
	ID: 535,
	Name: "wooden_pickaxe",
	StackSize: 1,
}
var WoodenAxe = &Item{
	ID: 536,
	Name: "wooden_axe",
	StackSize: 1,
}
var StoneSword = &Item{
	ID: 537,
	Name: "stone_sword",
	StackSize: 1,
}
var StoneShovel = &Item{
	ID: 538,
	Name: "stone_shovel",
	StackSize: 1,
}
var StonePickaxe = &Item{
	ID: 539,
	Name: "stone_pickaxe",
	StackSize: 1,
}
var StoneAxe = &Item{
	ID: 540,
	Name: "stone_axe",
	StackSize: 1,
}
var DiamondSword = &Item{
	ID: 541,
	Name: "diamond_sword",
	StackSize: 1,
}
var DiamondShovel = &Item{
	ID: 542,
	Name: "diamond_shovel",
	StackSize: 1,
}
var DiamondPickaxe = &Item{
	ID: 543,
	Name: "diamond_pickaxe",
	StackSize: 1,
}
var DiamondAxe = &Item{
	ID: 544,
	Name: "diamond_axe",
	StackSize: 1,
}
var Stick = &Item{
	ID: 545,
	Name: "stick",
	StackSize: 64,
}
var Bowl = &Item{
	ID: 546,
	Name: "bowl",
	StackSize: 64,
}
var MushroomStew = &Item{
	ID: 547,
	Name: "mushroom_stew",
	StackSize: 1,
}
var GoldenSword = &Item{
	ID: 548,
	Name: "golden_sword",
	StackSize: 1,
}
var GoldenShovel = &Item{
	ID: 549,
	Name: "golden_shovel",
	StackSize: 1,
}
var GoldenPickaxe = &Item{
	ID: 550,
	Name: "golden_pickaxe",
	StackSize: 1,
}
var GoldenAxe = &Item{
	ID: 551,
	Name: "golden_axe",
	StackSize: 1,
}
var String = &Item{
	ID: 552,
	Name: "string",
	StackSize: 64,
}
var Feather = &Item{
	ID: 553,
	Name: "feather",
	StackSize: 64,
}
var Gunpowder = &Item{
	ID: 554,
	Name: "gunpowder",
	StackSize: 64,
}
var WoodenHoe = &Item{
	ID: 555,
	Name: "wooden_hoe",
	StackSize: 1,
}
var StoneHoe = &Item{
	ID: 556,
	Name: "stone_hoe",
	StackSize: 1,
}
var IronHoe = &Item{
	ID: 557,
	Name: "iron_hoe",
	StackSize: 1,
}
var DiamondHoe = &Item{
	ID: 558,
	Name: "diamond_hoe",
	StackSize: 1,
}
var GoldenHoe = &Item{
	ID: 559,
	Name: "golden_hoe",
	StackSize: 1,
}
var WheatSeeds = &Item{
	ID: 560,
	Name: "wheat_seeds",
	StackSize: 64,
}
var Wheat = &Item{
	ID: 561,
	Name: "wheat",
	StackSize: 64,
}
var Bread = &Item{
	ID: 562,
	Name: "bread",
	StackSize: 64,
}
var LeatherHelmet = &Item{
	ID: 563,
	Name: "leather_helmet",
	StackSize: 1,
}
var LeatherChestplate = &Item{
	ID: 564,
	Name: "leather_chestplate",
	StackSize: 1,
}
var LeatherLeggings = &Item{
	ID: 565,
	Name: "leather_leggings",
	StackSize: 1,
}
var LeatherBoots = &Item{
	ID: 566,
	Name: "leather_boots",
	StackSize: 1,
}
var ChainmailHelmet = &Item{
	ID: 567,
	Name: "chainmail_helmet",
	StackSize: 1,
}
var ChainmailChestplate = &Item{
	ID: 568,
	Name: "chainmail_chestplate",
	StackSize: 1,
}
var ChainmailLeggings = &Item{
	ID: 569,
	Name: "chainmail_leggings",
	StackSize: 1,
}
var ChainmailBoots = &Item{
	ID: 570,
	Name: "chainmail_boots",
	StackSize: 1,
}
var IronHelmet = &Item{
	ID: 571,
	Name: "iron_helmet",
	StackSize: 1,
}
var IronChestplate = &Item{
	ID: 572,
	Name: "iron_chestplate",
	StackSize: 1,
}
var IronLeggings = &Item{
	ID: 573,
	Name: "iron_leggings",
	StackSize: 1,
}
var IronBoots = &Item{
	ID: 574,
	Name: "iron_boots",
	StackSize: 1,
}
var DiamondHelmet = &Item{
	ID: 575,
	Name: "diamond_helmet",
	StackSize: 1,
}
var DiamondChestplate = &Item{
	ID: 576,
	Name: "diamond_chestplate",
	StackSize: 1,
}
var DiamondLeggings = &Item{
	ID: 577,
	Name: "diamond_leggings",
	StackSize: 1,
}
var DiamondBoots = &Item{
	ID: 578,
	Name: "diamond_boots",
	StackSize: 1,
}
var GoldenHelmet = &Item{
	ID: 579,
	Name: "golden_helmet",
	StackSize: 1,
}
var GoldenChestplate = &Item{
	ID: 580,
	Name: "golden_chestplate",
	StackSize: 1,
}
var GoldenLeggings = &Item{
	ID: 581,
	Name: "golden_leggings",
	StackSize: 1,
}
var GoldenBoots = &Item{
	ID: 582,
	Name: "golden_boots",
	StackSize: 1,
}
var Flint = &Item{
	ID: 583,
	Name: "flint",
	StackSize: 64,
}
var Porkchop = &Item{
	ID: 584,
	Name: "porkchop",
	StackSize: 64,
}
var CookedPorkchop = &Item{
	ID: 585,
	Name: "cooked_porkchop",
	StackSize: 64,
}
var Painting = &Item{
	ID: 586,
	Name: "painting",
	StackSize: 64,
}
var GoldenApple = &Item{
	ID: 587,
	Name: "golden_apple",
	StackSize: 64,
}
var EnchantedGoldenApple = &Item{
	ID: 588,
	Name: "enchanted_golden_apple",
	StackSize: 64,
}
var OakSign = &Item{
	ID: 589,
	Name: "oak_sign",
	StackSize: 16,
}
var SpruceSign = &Item{
	ID: 590,
	Name: "spruce_sign",
	StackSize: 16,
}
var BirchSign = &Item{
	ID: 591,
	Name: "birch_sign",
	StackSize: 16,
}
var JungleSign = &Item{
	ID: 592,
	Name: "jungle_sign",
	StackSize: 16,
}
var AcaciaSign = &Item{
	ID: 593,
	Name: "acacia_sign",
	StackSize: 16,
}
var DarkOakSign = &Item{
	ID: 594,
	Name: "dark_oak_sign",
	StackSize: 16,
}
var Bucket = &Item{
	ID: 595,
	Name: "bucket",
	StackSize: 16,
}
var WaterBucket = &Item{
	ID: 596,
	Name: "water_bucket",
	StackSize: 1,
}
var LavaBucket = &Item{
	ID: 597,
	Name: "lava_bucket",
	StackSize: 1,
}
var Minecart = &Item{
	ID: 598,
	Name: "minecart",
	StackSize: 1,
}
var Saddle = &Item{
	ID: 599,
	Name: "saddle",
	StackSize: 1,
}
var Redstone = &Item{
	ID: 600,
	Name: "redstone",
	StackSize: 64,
}
var Snowball = &Item{
	ID: 601,
	Name: "snowball",
	StackSize: 16,
}
var OakBoat = &Item{
	ID: 602,
	Name: "oak_boat",
	StackSize: 1,
}
var Leather = &Item{
	ID: 603,
	Name: "leather",
	StackSize: 64,
}
var MilkBucket = &Item{
	ID: 604,
	Name: "milk_bucket",
	StackSize: 1,
}
var PufferfishBucket = &Item{
	ID: 605,
	Name: "pufferfish_bucket",
	StackSize: 1,
}
var SalmonBucket = &Item{
	ID: 606,
	Name: "salmon_bucket",
	StackSize: 1,
}
var CodBucket = &Item{
	ID: 607,
	Name: "cod_bucket",
	StackSize: 1,
}
var TropicalFishBucket = &Item{
	ID: 608,
	Name: "tropical_fish_bucket",
	StackSize: 1,
}
var Brick = &Item{
	ID: 609,
	Name: "brick",
	StackSize: 64,
}
var ClayBall = &Item{
	ID: 610,
	Name: "clay_ball",
	StackSize: 64,
}
var SugarCane = &Item{
	ID: 611,
	Name: "sugar_cane",
	StackSize: 64,
}
var Kelp = &Item{
	ID: 612,
	Name: "kelp",
	StackSize: 64,
}
var DriedKelpBlock = &Item{
	ID: 613,
	Name: "dried_kelp_block",
	StackSize: 64,
}
var Bamboo = &Item{
	ID: 614,
	Name: "bamboo",
	StackSize: 64,
}
var Paper = &Item{
	ID: 615,
	Name: "paper",
	StackSize: 64,
}
var Book = &Item{
	ID: 616,
	Name: "book",
	StackSize: 64,
}
var SlimeBall = &Item{
	ID: 617,
	Name: "slime_ball",
	StackSize: 64,
}
var ChestMinecart = &Item{
	ID: 618,
	Name: "chest_minecart",
	StackSize: 1,
}
var FurnaceMinecart = &Item{
	ID: 619,
	Name: "furnace_minecart",
	StackSize: 1,
}
var Egg = &Item{
	ID: 620,
	Name: "egg",
	StackSize: 16,
}
var Compass = &Item{
	ID: 621,
	Name: "compass",
	StackSize: 64,
}
var FishingRod = &Item{
	ID: 622,
	Name: "fishing_rod",
	StackSize: 1,
}
var Clock = &Item{
	ID: 623,
	Name: "clock",
	StackSize: 64,
}
var GlowstoneDust = &Item{
	ID: 624,
	Name: "glowstone_dust",
	StackSize: 64,
}
var Cod = &Item{
	ID: 625,
	Name: "cod",
	StackSize: 64,
}
var Salmon = &Item{
	ID: 626,
	Name: "salmon",
	StackSize: 64,
}
var TropicalFish = &Item{
	ID: 627,
	Name: "tropical_fish",
	StackSize: 64,
}
var Pufferfish = &Item{
	ID: 628,
	Name: "pufferfish",
	StackSize: 64,
}
var CookedCod = &Item{
	ID: 629,
	Name: "cooked_cod",
	StackSize: 64,
}
var CookedSalmon = &Item{
	ID: 630,
	Name: "cooked_salmon",
	StackSize: 64,
}
var InkSac = &Item{
	ID: 631,
	Name: "ink_sac",
	StackSize: 64,
}
var RedDye = &Item{
	ID: 632,
	Name: "red_dye",
	StackSize: 64,
}
var GreenDye = &Item{
	ID: 633,
	Name: "green_dye",
	StackSize: 64,
}
var CocoaBeans = &Item{
	ID: 634,
	Name: "cocoa_beans",
	StackSize: 64,
}
var LapisLazuli = &Item{
	ID: 635,
	Name: "lapis_lazuli",
	StackSize: 64,
}
var PurpleDye = &Item{
	ID: 636,
	Name: "purple_dye",
	StackSize: 64,
}
var CyanDye = &Item{
	ID: 637,
	Name: "cyan_dye",
	StackSize: 64,
}
var LightGrayDye = &Item{
	ID: 638,
	Name: "light_gray_dye",
	StackSize: 64,
}
var GrayDye = &Item{
	ID: 639,
	Name: "gray_dye",
	StackSize: 64,
}
var PinkDye = &Item{
	ID: 640,
	Name: "pink_dye",
	StackSize: 64,
}
var LimeDye = &Item{
	ID: 641,
	Name: "lime_dye",
	StackSize: 64,
}
var YellowDye = &Item{
	ID: 642,
	Name: "yellow_dye",
	StackSize: 64,
}
var LightBlueDye = &Item{
	ID: 643,
	Name: "light_blue_dye",
	StackSize: 64,
}
var MagentaDye = &Item{
	ID: 644,
	Name: "magenta_dye",
	StackSize: 64,
}
var OrangeDye = &Item{
	ID: 645,
	Name: "orange_dye",
	StackSize: 64,
}
var BoneMeal = &Item{
	ID: 646,
	Name: "bone_meal",
	StackSize: 64,
}
var BlueDye = &Item{
	ID: 647,
	Name: "blue_dye",
	StackSize: 64,
}
var BrownDye = &Item{
	ID: 648,
	Name: "brown_dye",
	StackSize: 64,
}
var BlackDye = &Item{
	ID: 649,
	Name: "black_dye",
	StackSize: 64,
}
var WhiteDye = &Item{
	ID: 650,
	Name: "white_dye",
	StackSize: 64,
}
var Bone = &Item{
	ID: 651,
	Name: "bone",
	StackSize: 64,
}
var Sugar = &Item{
	ID: 652,
	Name: "sugar",
	StackSize: 64,
}
var Cake = &Item{
	ID: 653,
	Name: "cake",
	StackSize: 1,
}
var WhiteBed = &Item{
	ID: 654,
	Name: "white_bed",
	StackSize: 1,
}
var OrangeBed = &Item{
	ID: 655,
	Name: "orange_bed",
	StackSize: 1,
}
var MagentaBed = &Item{
	ID: 656,
	Name: "magenta_bed",
	StackSize: 1,
}
var LightBlueBed = &Item{
	ID: 657,
	Name: "light_blue_bed",
	StackSize: 1,
}
var YellowBed = &Item{
	ID: 658,
	Name: "yellow_bed",
	StackSize: 1,
}
var LimeBed = &Item{
	ID: 659,
	Name: "lime_bed",
	StackSize: 1,
}
var PinkBed = &Item{
	ID: 660,
	Name: "pink_bed",
	StackSize: 1,
}
var GrayBed = &Item{
	ID: 661,
	Name: "gray_bed",
	StackSize: 1,
}
var LightGrayBed = &Item{
	ID: 662,
	Name: "light_gray_bed",
	StackSize: 1,
}
var CyanBed = &Item{
	ID: 663,
	Name: "cyan_bed",
	StackSize: 1,
}
var PurpleBed = &Item{
	ID: 664,
	Name: "purple_bed",
	StackSize: 1,
}
var BlueBed = &Item{
	ID: 665,
	Name: "blue_bed",
	StackSize: 1,
}
var BrownBed = &Item{
	ID: 666,
	Name: "brown_bed",
	StackSize: 1,
}
var GreenBed = &Item{
	ID: 667,
	Name: "green_bed",
	StackSize: 1,
}
var RedBed = &Item{
	ID: 668,
	Name: "red_bed",
	StackSize: 1,
}
var BlackBed = &Item{
	ID: 669,
	Name: "black_bed",
	StackSize: 1,
}
var Cookie = &Item{
	ID: 670,
	Name: "cookie",
	StackSize: 64,
}
var FilledMap = &Item{
	ID: 671,
	Name: "filled_map",
	StackSize: 64,
}
var Shears = &Item{
	ID: 672,
	Name: "shears",
	StackSize: 1,
}
var MelonSlice = &Item{
	ID: 673,
	Name: "melon_slice",
	StackSize: 64,
}
var DriedKelp = &Item{
	ID: 674,
	Name: "dried_kelp",
	StackSize: 64,
}
var PumpkinSeeds = &Item{
	ID: 675,
	Name: "pumpkin_seeds",
	StackSize: 64,
}
var MelonSeeds = &Item{
	ID: 676,
	Name: "melon_seeds",
	StackSize: 64,
}
var Beef = &Item{
	ID: 677,
	Name: "beef",
	StackSize: 64,
}
var CookedBeef = &Item{
	ID: 678,
	Name: "cooked_beef",
	StackSize: 64,
}
var Chicken = &Item{
	ID: 679,
	Name: "chicken",
	StackSize: 64,
}
var CookedChicken = &Item{
	ID: 680,
	Name: "cooked_chicken",
	StackSize: 64,
}
var RottenFlesh = &Item{
	ID: 681,
	Name: "rotten_flesh",
	StackSize: 64,
}
var EnderPearl = &Item{
	ID: 682,
	Name: "ender_pearl",
	StackSize: 16,
}
var BlazeRod = &Item{
	ID: 683,
	Name: "blaze_rod",
	StackSize: 64,
}
var GhastTear = &Item{
	ID: 684,
	Name: "ghast_tear",
	StackSize: 64,
}
var GoldNugget = &Item{
	ID: 685,
	Name: "gold_nugget",
	StackSize: 64,
}
var NetherWart = &Item{
	ID: 686,
	Name: "nether_wart",
	StackSize: 64,
}
var Potion = &Item{
	ID: 687,
	Name: "potion",
	StackSize: 1,
}
var GlassBottle = &Item{
	ID: 688,
	Name: "glass_bottle",
	StackSize: 64,
}
var SpiderEye = &Item{
	ID: 689,
	Name: "spider_eye",
	StackSize: 64,
}
var FermentedSpiderEye = &Item{
	ID: 690,
	Name: "fermented_spider_eye",
	StackSize: 64,
}
var BlazePowder = &Item{
	ID: 691,
	Name: "blaze_powder",
	StackSize: 64,
}
var MagmaCream = &Item{
	ID: 692,
	Name: "magma_cream",
	StackSize: 64,
}
var BrewingStand = &Item{
	ID: 693,
	Name: "brewing_stand",
	StackSize: 64,
}
var Cauldron = &Item{
	ID: 694,
	Name: "cauldron",
	StackSize: 64,
}
var EnderEye = &Item{
	ID: 695,
	Name: "ender_eye",
	StackSize: 64,
}
var GlisteringMelonSlice = &Item{
	ID: 696,
	Name: "glistering_melon_slice",
	StackSize: 64,
}
var BatSpawnEgg = &Item{
	ID: 697,
	Name: "bat_spawn_egg",
	StackSize: 64,
}
var BeeSpawnEgg = &Item{
	ID: 698,
	Name: "bee_spawn_egg",
	StackSize: 64,
}
var BlazeSpawnEgg = &Item{
	ID: 699,
	Name: "blaze_spawn_egg",
	StackSize: 64,
}
var CatSpawnEgg = &Item{
	ID: 700,
	Name: "cat_spawn_egg",
	StackSize: 64,
}
var CaveSpiderSpawnEgg = &Item{
	ID: 701,
	Name: "cave_spider_spawn_egg",
	StackSize: 64,
}
var ChickenSpawnEgg = &Item{
	ID: 702,
	Name: "chicken_spawn_egg",
	StackSize: 64,
}
var CodSpawnEgg = &Item{
	ID: 703,
	Name: "cod_spawn_egg",
	StackSize: 64,
}
var CowSpawnEgg = &Item{
	ID: 704,
	Name: "cow_spawn_egg",
	StackSize: 64,
}
var CreeperSpawnEgg = &Item{
	ID: 705,
	Name: "creeper_spawn_egg",
	StackSize: 64,
}
var DolphinSpawnEgg = &Item{
	ID: 706,
	Name: "dolphin_spawn_egg",
	StackSize: 64,
}
var DonkeySpawnEgg = &Item{
	ID: 707,
	Name: "donkey_spawn_egg",
	StackSize: 64,
}
var DrownedSpawnEgg = &Item{
	ID: 708,
	Name: "drowned_spawn_egg",
	StackSize: 64,
}
var ElderGuardianSpawnEgg = &Item{
	ID: 709,
	Name: "elder_guardian_spawn_egg",
	StackSize: 64,
}
var EndermanSpawnEgg = &Item{
	ID: 710,
	Name: "enderman_spawn_egg",
	StackSize: 64,
}
var EndermiteSpawnEgg = &Item{
	ID: 711,
	Name: "endermite_spawn_egg",
	StackSize: 64,
}
var EvokerSpawnEgg = &Item{
	ID: 712,
	Name: "evoker_spawn_egg",
	StackSize: 64,
}
var FoxSpawnEgg = &Item{
	ID: 713,
	Name: "fox_spawn_egg",
	StackSize: 64,
}
var GhastSpawnEgg = &Item{
	ID: 714,
	Name: "ghast_spawn_egg",
	StackSize: 64,
}
var GuardianSpawnEgg = &Item{
	ID: 715,
	Name: "guardian_spawn_egg",
	StackSize: 64,
}
var HorseSpawnEgg = &Item{
	ID: 716,
	Name: "horse_spawn_egg",
	StackSize: 64,
}
var HuskSpawnEgg = &Item{
	ID: 717,
	Name: "husk_spawn_egg",
	StackSize: 64,
}
var LlamaSpawnEgg = &Item{
	ID: 718,
	Name: "llama_spawn_egg",
	StackSize: 64,
}
var MagmaCubeSpawnEgg = &Item{
	ID: 719,
	Name: "magma_cube_spawn_egg",
	StackSize: 64,
}
var MooshroomSpawnEgg = &Item{
	ID: 720,
	Name: "mooshroom_spawn_egg",
	StackSize: 64,
}
var MuleSpawnEgg = &Item{
	ID: 721,
	Name: "mule_spawn_egg",
	StackSize: 64,
}
var OcelotSpawnEgg = &Item{
	ID: 722,
	Name: "ocelot_spawn_egg",
	StackSize: 64,
}
var PandaSpawnEgg = &Item{
	ID: 723,
	Name: "panda_spawn_egg",
	StackSize: 64,
}
var ParrotSpawnEgg = &Item{
	ID: 724,
	Name: "parrot_spawn_egg",
	StackSize: 64,
}
var PhantomSpawnEgg = &Item{
	ID: 725,
	Name: "phantom_spawn_egg",
	StackSize: 64,
}
var PigSpawnEgg = &Item{
	ID: 726,
	Name: "pig_spawn_egg",
	StackSize: 64,
}
var PillagerSpawnEgg = &Item{
	ID: 727,
	Name: "pillager_spawn_egg",
	StackSize: 64,
}
var PolarBearSpawnEgg = &Item{
	ID: 728,
	Name: "polar_bear_spawn_egg",
	StackSize: 64,
}
var PufferfishSpawnEgg = &Item{
	ID: 729,
	Name: "pufferfish_spawn_egg",
	StackSize: 64,
}
var RabbitSpawnEgg = &Item{
	ID: 730,
	Name: "rabbit_spawn_egg",
	StackSize: 64,
}
var RavagerSpawnEgg = &Item{
	ID: 731,
	Name: "ravager_spawn_egg",
	StackSize: 64,
}
var SalmonSpawnEgg = &Item{
	ID: 732,
	Name: "salmon_spawn_egg",
	StackSize: 64,
}
var SheepSpawnEgg = &Item{
	ID: 733,
	Name: "sheep_spawn_egg",
	StackSize: 64,
}
var ShulkerSpawnEgg = &Item{
	ID: 734,
	Name: "shulker_spawn_egg",
	StackSize: 64,
}
var SilverfishSpawnEgg = &Item{
	ID: 735,
	Name: "silverfish_spawn_egg",
	StackSize: 64,
}
var SkeletonSpawnEgg = &Item{
	ID: 736,
	Name: "skeleton_spawn_egg",
	StackSize: 64,
}
var SkeletonHorseSpawnEgg = &Item{
	ID: 737,
	Name: "skeleton_horse_spawn_egg",
	StackSize: 64,
}
var SlimeSpawnEgg = &Item{
	ID: 738,
	Name: "slime_spawn_egg",
	StackSize: 64,
}
var SpiderSpawnEgg = &Item{
	ID: 739,
	Name: "spider_spawn_egg",
	StackSize: 64,
}
var SquidSpawnEgg = &Item{
	ID: 740,
	Name: "squid_spawn_egg",
	StackSize: 64,
}
var StraySpawnEgg = &Item{
	ID: 741,
	Name: "stray_spawn_egg",
	StackSize: 64,
}
var TraderLlamaSpawnEgg = &Item{
	ID: 742,
	Name: "trader_llama_spawn_egg",
	StackSize: 64,
}
var TropicalFishSpawnEgg = &Item{
	ID: 743,
	Name: "tropical_fish_spawn_egg",
	StackSize: 64,
}
var TurtleSpawnEgg = &Item{
	ID: 744,
	Name: "turtle_spawn_egg",
	StackSize: 64,
}
var VexSpawnEgg = &Item{
	ID: 745,
	Name: "vex_spawn_egg",
	StackSize: 64,
}
var VillagerSpawnEgg = &Item{
	ID: 746,
	Name: "villager_spawn_egg",
	StackSize: 64,
}
var VindicatorSpawnEgg = &Item{
	ID: 747,
	Name: "vindicator_spawn_egg",
	StackSize: 64,
}
var WanderingTraderSpawnEgg = &Item{
	ID: 748,
	Name: "wandering_trader_spawn_egg",
	StackSize: 64,
}
var WitchSpawnEgg = &Item{
	ID: 749,
	Name: "witch_spawn_egg",
	StackSize: 64,
}
var WitherSkeletonSpawnEgg = &Item{
	ID: 750,
	Name: "wither_skeleton_spawn_egg",
	StackSize: 64,
}
var WolfSpawnEgg = &Item{
	ID: 751,
	Name: "wolf_spawn_egg",
	StackSize: 64,
}
var ZombieSpawnEgg = &Item{
	ID: 752,
	Name: "zombie_spawn_egg",
	StackSize: 64,
}
var ZombieHorseSpawnEgg = &Item{
	ID: 753,
	Name: "zombie_horse_spawn_egg",
	StackSize: 64,
}
var ZombiePigmanSpawnEgg = &Item{
	ID: 754,
	Name: "zombie_pigman_spawn_egg",
	StackSize: 64,
}
var ZombieVillagerSpawnEgg = &Item{
	ID: 755,
	Name: "zombie_villager_spawn_egg",
	StackSize: 64,
}
var ExperienceBottle = &Item{
	ID: 756,
	Name: "experience_bottle",
	StackSize: 64,
}
var FireCharge = &Item{
	ID: 757,
	Name: "fire_charge",
	StackSize: 64,
}
var WritableBook = &Item{
	ID: 758,
	Name: "writable_book",
	StackSize: 1,
}
var WrittenBook = &Item{
	ID: 759,
	Name: "written_book",
	StackSize: 16,
}
var Emerald = &Item{
	ID: 760,
	Name: "emerald",
	StackSize: 64,
}
var ItemFrame = &Item{
	ID: 761,
	Name: "item_frame",
	StackSize: 64,
}
var FlowerPot = &Item{
	ID: 762,
	Name: "flower_pot",
	StackSize: 64,
}
var Carrot = &Item{
	ID: 763,
	Name: "carrot",
	StackSize: 64,
}
var Potato = &Item{
	ID: 764,
	Name: "potato",
	StackSize: 64,
}
var BakedPotato = &Item{
	ID: 765,
	Name: "baked_potato",
	StackSize: 64,
}
var PoisonousPotato = &Item{
	ID: 766,
	Name: "poisonous_potato",
	StackSize: 64,
}
var Map = &Item{
	ID: 767,
	Name: "map",
	StackSize: 64,
}
var GoldenCarrot = &Item{
	ID: 768,
	Name: "golden_carrot",
	StackSize: 64,
}
var SkeletonSkull = &Item{
	ID: 769,
	Name: "skeleton_skull",
	StackSize: 64,
}
var WitherSkeletonSkull = &Item{
	ID: 770,
	Name: "wither_skeleton_skull",
	StackSize: 64,
}
var PlayerHead = &Item{
	ID: 771,
	Name: "player_head",
	StackSize: 64,
}
var ZombieHead = &Item{
	ID: 772,
	Name: "zombie_head",
	StackSize: 64,
}
var CreeperHead = &Item{
	ID: 773,
	Name: "creeper_head",
	StackSize: 64,
}
var DragonHead = &Item{
	ID: 774,
	Name: "dragon_head",
	StackSize: 64,
}
var CarrotOnAStick = &Item{
	ID: 775,
	Name: "carrot_on_a_stick",
	StackSize: 1,
}
var NetherStar = &Item{
	ID: 776,
	Name: "nether_star",
	StackSize: 64,
}
var PumpkinPie = &Item{
	ID: 777,
	Name: "pumpkin_pie",
	StackSize: 64,
}
var FireworkRocket = &Item{
	ID: 778,
	Name: "firework_rocket",
	StackSize: 64,
}
var FireworkStar = &Item{
	ID: 779,
	Name: "firework_star",
	StackSize: 64,
}
var EnchantedBook = &Item{
	ID: 780,
	Name: "enchanted_book",
	StackSize: 1,
}
var NetherBrick = &Item{
	ID: 781,
	Name: "nether_brick",
	StackSize: 64,
}
var Quartz = &Item{
	ID: 782,
	Name: "quartz",
	StackSize: 64,
}
var TntMinecart = &Item{
	ID: 783,
	Name: "tnt_minecart",
	StackSize: 1,
}
var HopperMinecart = &Item{
	ID: 784,
	Name: "hopper_minecart",
	StackSize: 1,
}
var PrismarineShard = &Item{
	ID: 785,
	Name: "prismarine_shard",
	StackSize: 64,
}
var PrismarineCrystals = &Item{
	ID: 786,
	Name: "prismarine_crystals",
	StackSize: 64,
}
var Rabbit = &Item{
	ID: 787,
	Name: "rabbit",
	StackSize: 64,
}
var CookedRabbit = &Item{
	ID: 788,
	Name: "cooked_rabbit",
	StackSize: 64,
}
var RabbitStew = &Item{
	ID: 789,
	Name: "rabbit_stew",
	StackSize: 1,
}
var RabbitFoot = &Item{
	ID: 790,
	Name: "rabbit_foot",
	StackSize: 64,
}
var RabbitHide = &Item{
	ID: 791,
	Name: "rabbit_hide",
	StackSize: 64,
}
var ArmorStand = &Item{
	ID: 792,
	Name: "armor_stand",
	StackSize: 16,
}
var IronHorseArmor = &Item{
	ID: 793,
	Name: "iron_horse_armor",
	StackSize: 1,
}
var GoldenHorseArmor = &Item{
	ID: 794,
	Name: "golden_horse_armor",
	StackSize: 1,
}
var DiamondHorseArmor = &Item{
	ID: 795,
	Name: "diamond_horse_armor",
	StackSize: 1,
}
var LeatherHorseArmor = &Item{
	ID: 796,
	Name: "leather_horse_armor",
	StackSize: 1,
}
var Lead = &Item{
	ID: 797,
	Name: "lead",
	StackSize: 64,
}
var NameTag = &Item{
	ID: 798,
	Name: "name_tag",
	StackSize: 64,
}
var CommandBlockMinecart = &Item{
	ID: 799,
	Name: "command_block_minecart",
	StackSize: 1,
}
var Mutton = &Item{
	ID: 800,
	Name: "mutton",
	StackSize: 64,
}
var CookedMutton = &Item{
	ID: 801,
	Name: "cooked_mutton",
	StackSize: 64,
}
var WhiteBanner = &Item{
	ID: 802,
	Name: "white_banner",
	StackSize: 16,
}
var OrangeBanner = &Item{
	ID: 803,
	Name: "orange_banner",
	StackSize: 16,
}
var MagentaBanner = &Item{
	ID: 804,
	Name: "magenta_banner",
	StackSize: 16,
}
var LightBlueBanner = &Item{
	ID: 805,
	Name: "light_blue_banner",
	StackSize: 16,
}
var YellowBanner = &Item{
	ID: 806,
	Name: "yellow_banner",
	StackSize: 16,
}
var LimeBanner = &Item{
	ID: 807,
	Name: "lime_banner",
	StackSize: 16,
}
var PinkBanner = &Item{
	ID: 808,
	Name: "pink_banner",
	StackSize: 16,
}
var GrayBanner = &Item{
	ID: 809,
	Name: "gray_banner",
	StackSize: 16,
}
var LightGrayBanner = &Item{
	ID: 810,
	Name: "light_gray_banner",
	StackSize: 16,
}
var CyanBanner = &Item{
	ID: 811,
	Name: "cyan_banner",
	StackSize: 16,
}
var PurpleBanner = &Item{
	ID: 812,
	Name: "purple_banner",
	StackSize: 16,
}
var BlueBanner = &Item{
	ID: 813,
	Name: "blue_banner",
	StackSize: 16,
}
var BrownBanner = &Item{
	ID: 814,
	Name: "brown_banner",
	StackSize: 16,
}
var GreenBanner = &Item{
	ID: 815,
	Name: "green_banner",
	StackSize: 16,
}
var RedBanner = &Item{
	ID: 816,
	Name: "red_banner",
	StackSize: 16,
}
var BlackBanner = &Item{
	ID: 817,
	Name: "black_banner",
	StackSize: 16,
}
var EndCrystal = &Item{
	ID: 818,
	Name: "end_crystal",
	StackSize: 64,
}
var ChorusFruit = &Item{
	ID: 819,
	Name: "chorus_fruit",
	StackSize: 64,
}
var PoppedChorusFruit = &Item{
	ID: 820,
	Name: "popped_chorus_fruit",
	StackSize: 64,
}
var Beetroot = &Item{
	ID: 821,
	Name: "beetroot",
	StackSize: 64,
}
var BeetrootSeeds = &Item{
	ID: 822,
	Name: "beetroot_seeds",
	StackSize: 64,
}
var BeetrootSoup = &Item{
	ID: 823,
	Name: "beetroot_soup",
	StackSize: 1,
}
var DragonBreath = &Item{
	ID: 824,
	Name: "dragon_breath",
	StackSize: 64,
}
var SplashPotion = &Item{
	ID: 825,
	Name: "splash_potion",
	StackSize: 1,
}
var SpectralArrow = &Item{
	ID: 826,
	Name: "spectral_arrow",
	StackSize: 64,
}
var TippedArrow = &Item{
	ID: 827,
	Name: "tipped_arrow",
	StackSize: 64,
}
var LingeringPotion = &Item{
	ID: 828,
	Name: "lingering_potion",
	StackSize: 1,
}
var Shield = &Item{
	ID: 829,
	Name: "shield",
	StackSize: 1,
}
var Elytra = &Item{
	ID: 830,
	Name: "elytra",
	StackSize: 1,
}
var SpruceBoat = &Item{
	ID: 831,
	Name: "spruce_boat",
	StackSize: 1,
}
var BirchBoat = &Item{
	ID: 832,
	Name: "birch_boat",
	StackSize: 1,
}
var JungleBoat = &Item{
	ID: 833,
	Name: "jungle_boat",
	StackSize: 1,
}
var AcaciaBoat = &Item{
	ID: 834,
	Name: "acacia_boat",
	StackSize: 1,
}
var DarkOakBoat = &Item{
	ID: 835,
	Name: "dark_oak_boat",
	StackSize: 1,
}
var TotemOfUndying = &Item{
	ID: 836,
	Name: "totem_of_undying",
	StackSize: 1,
}
var ShulkerShell = &Item{
	ID: 837,
	Name: "shulker_shell",
	StackSize: 64,
}
var IronNugget = &Item{
	ID: 838,
	Name: "iron_nugget",
	StackSize: 64,
}
var KnowledgeBook = &Item{
	ID: 839,
	Name: "knowledge_book",
	StackSize: 1,
}
var DebugStick = &Item{
	ID: 840,
	Name: "debug_stick",
	StackSize: 1,
}
var MusicDisc_13 = &Item{
	ID: 841,
	Name: "music_disc_13",
	StackSize: 1,
}
var MusicDiscCat = &Item{
	ID: 842,
	Name: "music_disc_cat",
	StackSize: 1,
}
var MusicDiscBlocks = &Item{
	ID: 843,
	Name: "music_disc_blocks",
	StackSize: 1,
}
var MusicDiscChirp = &Item{
	ID: 844,
	Name: "music_disc_chirp",
	StackSize: 1,
}
var MusicDiscFar = &Item{
	ID: 845,
	Name: "music_disc_far",
	StackSize: 1,
}
var MusicDiscMall = &Item{
	ID: 846,
	Name: "music_disc_mall",
	StackSize: 1,
}
var MusicDiscMellohi = &Item{
	ID: 847,
	Name: "music_disc_mellohi",
	StackSize: 1,
}
var MusicDiscStal = &Item{
	ID: 848,
	Name: "music_disc_stal",
	StackSize: 1,
}
var MusicDiscStrad = &Item{
	ID: 849,
	Name: "music_disc_strad",
	StackSize: 1,
}
var MusicDiscWard = &Item{
	ID: 850,
	Name: "music_disc_ward",
	StackSize: 1,
}
var MusicDisc_11 = &Item{
	ID: 851,
	Name: "music_disc_11",
	StackSize: 1,
}
var MusicDiscWait = &Item{
	ID: 852,
	Name: "music_disc_wait",
	StackSize: 1,
}
var Trident = &Item{
	ID: 853,
	Name: "trident",
	StackSize: 1,
}
var PhantomMembrane = &Item{
	ID: 854,
	Name: "phantom_membrane",
	StackSize: 64,
}
var NautilusShell = &Item{
	ID: 855,
	Name: "nautilus_shell",
	StackSize: 64,
}
var HeartOfTheSea = &Item{
	ID: 856,
	Name: "heart_of_the_sea",
	StackSize: 64,
}
var Crossbow = &Item{
	ID: 857,
	Name: "crossbow",
	StackSize: 1,
}
var SuspiciousStew = &Item{
	ID: 858,
	Name: "suspicious_stew",
	StackSize: 1,
}
var Loom = &Item{
	ID: 859,
	Name: "loom",
	StackSize: 64,
}
var FlowerBannerPattern = &Item{
	ID: 860,
	Name: "flower_banner_pattern",
	StackSize: 1,
}
var CreeperBannerPattern = &Item{
	ID: 861,
	Name: "creeper_banner_pattern",
	StackSize: 1,
}
var SkullBannerPattern = &Item{
	ID: 862,
	Name: "skull_banner_pattern",
	StackSize: 1,
}
var MojangBannerPattern = &Item{
	ID: 863,
	Name: "mojang_banner_pattern",
	StackSize: 1,
}
var GlobeBannerPattern = &Item{
	ID: 864,
	Name: "globe_banner_pattern",
	StackSize: 1,
}
var Barrel = &Item{
	ID: 865,
	Name: "barrel",
	StackSize: 64,
}
var Smoker = &Item{
	ID: 866,
	Name: "smoker",
	StackSize: 64,
}
var BlastFurnace = &Item{
	ID: 867,
	Name: "blast_furnace",
	StackSize: 64,
}
var CartographyTable = &Item{
	ID: 868,
	Name: "cartography_table",
	StackSize: 64,
}
var FletchingTable = &Item{
	ID: 869,
	Name: "fletching_table",
	StackSize: 64,
}
var Grindstone = &Item{
	ID: 870,
	Name: "grindstone",
	StackSize: 64,
}
var Lectern = &Item{
	ID: 871,
	Name: "lectern",
	StackSize: 64,
}
var SmithingTable = &Item{
	ID: 872,
	Name: "smithing_table",
	StackSize: 64,
}
var Stonecutter = &Item{
	ID: 873,
	Name: "stonecutter",
	StackSize: 64,
}
var Bell = &Item{
	ID: 874,
	Name: "bell",
	StackSize: 64,
}
var Lantern = &Item{
	ID: 875,
	Name: "lantern",
	StackSize: 64,
}
var SweetBerries = &Item{
	ID: 876,
	Name: "sweet_berries",
	StackSize: 64,
}
var Campfire = &Item{
	ID: 877,
	Name: "campfire",
	StackSize: 64,
}
var Honeycomb = &Item{
	ID: 878,
	Name: "honeycomb",
	StackSize: 64,
}
var BeeNest = &Item{
	ID: 879,
	Name: "bee_nest",
	StackSize: 64,
}
var Beehive = &Item{
	ID: 880,
	Name: "beehive",
	StackSize: 64,
}
var HoneyBottle = &Item{
	ID: 881,
	Name: "honey_bottle",
	StackSize: 16,
}
var HoneyBlock = &Item{
	ID: 882,
	Name: "honey_block",
	StackSize: 64,
}
var HoneycombBlock = &Item{
	ID: 883,
	Name: "honeycomb_block",
	StackSize: 64,
}

var items = [...]*Item{
	0: Air,
	1: Stone,
	2: Granite,
	3: PolishedGranite,
	4: Diorite,
	5: PolishedDiorite,
	6: Andesite,
	7: PolishedAndesite,
	8: GrassBlock,
	9: Dirt,
	10: CoarseDirt,
	11: Podzol,
	12: Cobblestone,
	13: OakPlanks,
	14: SprucePlanks,
	15: BirchPlanks,
	16: JunglePlanks,
	17: AcaciaPlanks,
	18: DarkOakPlanks,
	19: OakSapling,
	20: SpruceSapling,
	21: BirchSapling,
	22: JungleSapling,
	23: AcaciaSapling,
	24: DarkOakSapling,
	25: Bedrock,
	26: Sand,
	27: RedSand,
	28: Gravel,
	29: GoldOre,
	30: IronOre,
	31: CoalOre,
	32: OakLog,
	33: SpruceLog,
	34: BirchLog,
	35: JungleLog,
	36: AcaciaLog,
	37: DarkOakLog,
	38: StrippedOakLog,
	39: StrippedSpruceLog,
	40: StrippedBirchLog,
	41: StrippedJungleLog,
	42: StrippedAcaciaLog,
	43: StrippedDarkOakLog,
	44: StrippedOakWood,
	45: StrippedSpruceWood,
	46: StrippedBirchWood,
	47: StrippedJungleWood,
	48: StrippedAcaciaWood,
	49: StrippedDarkOakWood,
	50: OakWood,
	51: SpruceWood,
	52: BirchWood,
	53: JungleWood,
	54: AcaciaWood,
	55: DarkOakWood,
	56: OakLeaves,
	57: SpruceLeaves,
	58: BirchLeaves,
	59: JungleLeaves,
	60: AcaciaLeaves,
	61: DarkOakLeaves,
	62: Sponge,
	63: WetSponge,
	64: Glass,
	65: LapisOre,
	66: LapisBlock,
	67: Dispenser,
	68: Sandstone,
	69: ChiseledSandstone,
	70: CutSandstone,
	71: NoteBlock,
	72: PoweredRail,
	73: DetectorRail,
	74: StickyPiston,
	75: Cobweb,
	76: Grass,
	77: Fern,
	78: DeadBush,
	79: Seagrass,
	80: SeaPickle,
	81: Piston,
	82: WhiteWool,
	83: OrangeWool,
	84: MagentaWool,
	85: LightBlueWool,
	86: YellowWool,
	87: LimeWool,
	88: PinkWool,
	89: GrayWool,
	90: LightGrayWool,
	91: CyanWool,
	92: PurpleWool,
	93: BlueWool,
	94: BrownWool,
	95: GreenWool,
	96: RedWool,
	97: BlackWool,
	98: Dandelion,
	99: Poppy,
	100: BlueOrchid,
	101: Allium,
	102: AzureBluet,
	103: RedTulip,
	104: OrangeTulip,
	105: WhiteTulip,
	106: PinkTulip,
	107: OxeyeDaisy,
	108: Cornflower,
	109: LilyOfTheValley,
	110: WitherRose,
	111: BrownMushroom,
	112: RedMushroom,
	113: GoldBlock,
	114: IronBlock,
	115: OakSlab,
	116: SpruceSlab,
	117: BirchSlab,
	118: JungleSlab,
	119: AcaciaSlab,
	120: DarkOakSlab,
	121: StoneSlab,
	122: SmoothStoneSlab,
	123: SandstoneSlab,
	124: CutSandstoneSlab,
	125: PetrifiedOakSlab,
	126: CobblestoneSlab,
	127: BrickSlab,
	128: StoneBrickSlab,
	129: NetherBrickSlab,
	130: QuartzSlab,
	131: RedSandstoneSlab,
	132: CutRedSandstoneSlab,
	133: PurpurSlab,
	134: PrismarineSlab,
	135: PrismarineBrickSlab,
	136: DarkPrismarineSlab,
	137: SmoothQuartz,
	138: SmoothRedSandstone,
	139: SmoothSandstone,
	140: SmoothStone,
	141: Bricks,
	142: Tnt,
	143: Bookshelf,
	144: MossyCobblestone,
	145: Obsidian,
	146: Torch,
	147: EndRod,
	148: ChorusPlant,
	149: ChorusFlower,
	150: PurpurBlock,
	151: PurpurPillar,
	152: PurpurStairs,
	153: Spawner,
	154: OakStairs,
	155: Chest,
	156: DiamondOre,
	157: DiamondBlock,
	158: CraftingTable,
	159: Farmland,
	160: Furnace,
	161: Ladder,
	162: Rail,
	163: CobblestoneStairs,
	164: Lever,
	165: StonePressurePlate,
	166: OakPressurePlate,
	167: SprucePressurePlate,
	168: BirchPressurePlate,
	169: JunglePressurePlate,
	170: AcaciaPressurePlate,
	171: DarkOakPressurePlate,
	172: RedstoneOre,
	173: RedstoneTorch,
	174: StoneButton,
	175: Snow,
	176: Ice,
	177: SnowBlock,
	178: Cactus,
	179: Clay,
	180: Jukebox,
	181: OakFence,
	182: SpruceFence,
	183: BirchFence,
	184: JungleFence,
	185: AcaciaFence,
	186: DarkOakFence,
	187: Pumpkin,
	188: CarvedPumpkin,
	189: Netherrack,
	190: SoulSand,
	191: Glowstone,
	192: JackOLantern,
	193: OakTrapdoor,
	194: SpruceTrapdoor,
	195: BirchTrapdoor,
	196: JungleTrapdoor,
	197: AcaciaTrapdoor,
	198: DarkOakTrapdoor,
	199: InfestedStone,
	200: InfestedCobblestone,
	201: InfestedStoneBricks,
	202: InfestedMossyStoneBricks,
	203: InfestedCrackedStoneBricks,
	204: InfestedChiseledStoneBricks,
	205: StoneBricks,
	206: MossyStoneBricks,
	207: CrackedStoneBricks,
	208: ChiseledStoneBricks,
	209: BrownMushroomBlock,
	210: RedMushroomBlock,
	211: MushroomStem,
	212: IronBars,
	213: GlassPane,
	214: Melon,
	215: Vine,
	216: OakFenceGate,
	217: SpruceFenceGate,
	218: BirchFenceGate,
	219: JungleFenceGate,
	220: AcaciaFenceGate,
	221: DarkOakFenceGate,
	222: BrickStairs,
	223: StoneBrickStairs,
	224: Mycelium,
	225: LilyPad,
	226: NetherBricks,
	227: NetherBrickFence,
	228: NetherBrickStairs,
	229: EnchantingTable,
	230: EndPortalFrame,
	231: EndStone,
	232: EndStoneBricks,
	233: DragonEgg,
	234: RedstoneLamp,
	235: SandstoneStairs,
	236: EmeraldOre,
	237: EnderChest,
	238: TripwireHook,
	239: EmeraldBlock,
	240: SpruceStairs,
	241: BirchStairs,
	242: JungleStairs,
	243: CommandBlock,
	244: Beacon,
	245: CobblestoneWall,
	246: MossyCobblestoneWall,
	247: BrickWall,
	248: PrismarineWall,
	249: RedSandstoneWall,
	250: MossyStoneBrickWall,
	251: GraniteWall,
	252: StoneBrickWall,
	253: NetherBrickWall,
	254: AndesiteWall,
	255: RedNetherBrickWall,
	256: SandstoneWall,
	257: EndStoneBrickWall,
	258: DioriteWall,
	259: OakButton,
	260: SpruceButton,
	261: BirchButton,
	262: JungleButton,
	263: AcaciaButton,
	264: DarkOakButton,
	265: Anvil,
	266: ChippedAnvil,
	267: DamagedAnvil,
	268: TrappedChest,
	269: LightWeightedPressurePlate,
	270: HeavyWeightedPressurePlate,
	271: DaylightDetector,
	272: RedstoneBlock,
	273: NetherQuartzOre,
	274: Hopper,
	275: ChiseledQuartzBlock,
	276: QuartzBlock,
	277: QuartzPillar,
	278: QuartzStairs,
	279: ActivatorRail,
	280: Dropper,
	281: WhiteTerracotta,
	282: OrangeTerracotta,
	283: MagentaTerracotta,
	284: LightBlueTerracotta,
	285: YellowTerracotta,
	286: LimeTerracotta,
	287: PinkTerracotta,
	288: GrayTerracotta,
	289: LightGrayTerracotta,
	290: CyanTerracotta,
	291: PurpleTerracotta,
	292: BlueTerracotta,
	293: BrownTerracotta,
	294: GreenTerracotta,
	295: RedTerracotta,
	296: BlackTerracotta,
	297: Barrier,
	298: IronTrapdoor,
	299: HayBlock,
	300: WhiteCarpet,
	301: OrangeCarpet,
	302: MagentaCarpet,
	303: LightBlueCarpet,
	304: YellowCarpet,
	305: LimeCarpet,
	306: PinkCarpet,
	307: GrayCarpet,
	308: LightGrayCarpet,
	309: CyanCarpet,
	310: PurpleCarpet,
	311: BlueCarpet,
	312: BrownCarpet,
	313: GreenCarpet,
	314: RedCarpet,
	315: BlackCarpet,
	316: Terracotta,
	317: CoalBlock,
	318: PackedIce,
	319: AcaciaStairs,
	320: DarkOakStairs,
	321: SlimeBlock,
	322: GrassPath,
	323: Sunflower,
	324: Lilac,
	325: RoseBush,
	326: Peony,
	327: TallGrass,
	328: LargeFern,
	329: WhiteStainedGlass,
	330: OrangeStainedGlass,
	331: MagentaStainedGlass,
	332: LightBlueStainedGlass,
	333: YellowStainedGlass,
	334: LimeStainedGlass,
	335: PinkStainedGlass,
	336: GrayStainedGlass,
	337: LightGrayStainedGlass,
	338: CyanStainedGlass,
	339: PurpleStainedGlass,
	340: BlueStainedGlass,
	341: BrownStainedGlass,
	342: GreenStainedGlass,
	343: RedStainedGlass,
	344: BlackStainedGlass,
	345: WhiteStainedGlassPane,
	346: OrangeStainedGlassPane,
	347: MagentaStainedGlassPane,
	348: LightBlueStainedGlassPane,
	349: YellowStainedGlassPane,
	350: LimeStainedGlassPane,
	351: PinkStainedGlassPane,
	352: GrayStainedGlassPane,
	353: LightGrayStainedGlassPane,
	354: CyanStainedGlassPane,
	355: PurpleStainedGlassPane,
	356: BlueStainedGlassPane,
	357: BrownStainedGlassPane,
	358: GreenStainedGlassPane,
	359: RedStainedGlassPane,
	360: BlackStainedGlassPane,
	361: Prismarine,
	362: PrismarineBricks,
	363: DarkPrismarine,
	364: PrismarineStairs,
	365: PrismarineBrickStairs,
	366: DarkPrismarineStairs,
	367: SeaLantern,
	368: RedSandstone,
	369: ChiseledRedSandstone,
	370: CutRedSandstone,
	371: RedSandstoneStairs,
	372: RepeatingCommandBlock,
	373: ChainCommandBlock,
	374: MagmaBlock,
	375: NetherWartBlock,
	376: RedNetherBricks,
	377: BoneBlock,
	378: StructureVoid,
	379: Observer,
	380: ShulkerBox,
	381: WhiteShulkerBox,
	382: OrangeShulkerBox,
	383: MagentaShulkerBox,
	384: LightBlueShulkerBox,
	385: YellowShulkerBox,
	386: LimeShulkerBox,
	387: PinkShulkerBox,
	388: GrayShulkerBox,
	389: LightGrayShulkerBox,
	390: CyanShulkerBox,
	391: PurpleShulkerBox,
	392: BlueShulkerBox,
	393: BrownShulkerBox,
	394: GreenShulkerBox,
	395: RedShulkerBox,
	396: BlackShulkerBox,
	397: WhiteGlazedTerracotta,
	398: OrangeGlazedTerracotta,
	399: MagentaGlazedTerracotta,
	400: LightBlueGlazedTerracotta,
	401: YellowGlazedTerracotta,
	402: LimeGlazedTerracotta,
	403: PinkGlazedTerracotta,
	404: GrayGlazedTerracotta,
	405: LightGrayGlazedTerracotta,
	406: CyanGlazedTerracotta,
	407: PurpleGlazedTerracotta,
	408: BlueGlazedTerracotta,
	409: BrownGlazedTerracotta,
	410: GreenGlazedTerracotta,
	411: RedGlazedTerracotta,
	412: BlackGlazedTerracotta,
	413: WhiteConcrete,
	414: OrangeConcrete,
	415: MagentaConcrete,
	416: LightBlueConcrete,
	417: YellowConcrete,
	418: LimeConcrete,
	419: PinkConcrete,
	420: GrayConcrete,
	421: LightGrayConcrete,
	422: CyanConcrete,
	423: PurpleConcrete,
	424: BlueConcrete,
	425: BrownConcrete,
	426: GreenConcrete,
	427: RedConcrete,
	428: BlackConcrete,
	429: WhiteConcretePowder,
	430: OrangeConcretePowder,
	431: MagentaConcretePowder,
	432: LightBlueConcretePowder,
	433: YellowConcretePowder,
	434: LimeConcretePowder,
	435: PinkConcretePowder,
	436: GrayConcretePowder,
	437: LightGrayConcretePowder,
	438: CyanConcretePowder,
	439: PurpleConcretePowder,
	440: BlueConcretePowder,
	441: BrownConcretePowder,
	442: GreenConcretePowder,
	443: RedConcretePowder,
	444: BlackConcretePowder,
	445: TurtleEgg,
	446: DeadTubeCoralBlock,
	447: DeadBrainCoralBlock,
	448: DeadBubbleCoralBlock,
	449: DeadFireCoralBlock,
	450: DeadHornCoralBlock,
	451: TubeCoralBlock,
	452: BrainCoralBlock,
	453: BubbleCoralBlock,
	454: FireCoralBlock,
	455: HornCoralBlock,
	456: TubeCoral,
	457: BrainCoral,
	458: BubbleCoral,
	459: FireCoral,
	460: HornCoral,
	461: DeadBrainCoral,
	462: DeadBubbleCoral,
	463: DeadFireCoral,
	464: DeadHornCoral,
	465: DeadTubeCoral,
	466: TubeCoralFan,
	467: BrainCoralFan,
	468: BubbleCoralFan,
	469: FireCoralFan,
	470: HornCoralFan,
	471: DeadTubeCoralFan,
	472: DeadBrainCoralFan,
	473: DeadBubbleCoralFan,
	474: DeadFireCoralFan,
	475: DeadHornCoralFan,
	476: BlueIce,
	477: Conduit,
	478: PolishedGraniteStairs,
	479: SmoothRedSandstoneStairs,
	480: MossyStoneBrickStairs,
	481: PolishedDioriteStairs,
	482: MossyCobblestoneStairs,
	483: EndStoneBrickStairs,
	484: StoneStairs,
	485: SmoothSandstoneStairs,
	486: SmoothQuartzStairs,
	487: GraniteStairs,
	488: AndesiteStairs,
	489: RedNetherBrickStairs,
	490: PolishedAndesiteStairs,
	491: DioriteStairs,
	492: PolishedGraniteSlab,
	493: SmoothRedSandstoneSlab,
	494: MossyStoneBrickSlab,
	495: PolishedDioriteSlab,
	496: MossyCobblestoneSlab,
	497: EndStoneBrickSlab,
	498: SmoothSandstoneSlab,
	499: SmoothQuartzSlab,
	500: GraniteSlab,
	501: AndesiteSlab,
	502: RedNetherBrickSlab,
	503: PolishedAndesiteSlab,
	504: DioriteSlab,
	505: Scaffolding,
	506: IronDoor,
	507: OakDoor,
	508: SpruceDoor,
	509: BirchDoor,
	510: JungleDoor,
	511: AcaciaDoor,
	512: DarkOakDoor,
	513: Repeater,
	514: Comparator,
	515: StructureBlock,
	516: Jigsaw,
	517: Composter,
	518: TurtleHelmet,
	519: Scute,
	520: IronShovel,
	521: IronPickaxe,
	522: IronAxe,
	523: FlintAndSteel,
	524: Apple,
	525: Bow,
	526: Arrow,
	527: Coal,
	528: Charcoal,
	529: Diamond,
	530: IronIngot,
	531: GoldIngot,
	532: IronSword,
	533: WoodenSword,
	534: WoodenShovel,
	535: WoodenPickaxe,
	536: WoodenAxe,
	537: StoneSword,
	538: StoneShovel,
	539: StonePickaxe,
	540: StoneAxe,
	541: DiamondSword,
	542: DiamondShovel,
	543: DiamondPickaxe,
	544: DiamondAxe,
	545: Stick,
	546: Bowl,
	547: MushroomStew,
	548: GoldenSword,
	549: GoldenShovel,
	550: GoldenPickaxe,
	551: GoldenAxe,
	552: String,
	553: Feather,
	554: Gunpowder,
	555: WoodenHoe,
	556: StoneHoe,
	557: IronHoe,
	558: DiamondHoe,
	559: GoldenHoe,
	560: WheatSeeds,
	561: Wheat,
	562: Bread,
	563: LeatherHelmet,
	564: LeatherChestplate,
	565: LeatherLeggings,
	566: LeatherBoots,
	567: ChainmailHelmet,
	568: ChainmailChestplate,
	569: ChainmailLeggings,
	570: ChainmailBoots,
	571: IronHelmet,
	572: IronChestplate,
	573: IronLeggings,
	574: IronBoots,
	575: DiamondHelmet,
	576: DiamondChestplate,
	577: DiamondLeggings,
	578: DiamondBoots,
	579: GoldenHelmet,
	580: GoldenChestplate,
	581: GoldenLeggings,
	582: GoldenBoots,
	583: Flint,
	584: Porkchop,
	585: CookedPorkchop,
	586: Painting,
	587: GoldenApple,
	588: EnchantedGoldenApple,
	589: OakSign,
	590: SpruceSign,
	591: BirchSign,
	592: JungleSign,
	593: AcaciaSign,
	594: DarkOakSign,
	595: Bucket,
	596: WaterBucket,
	597: LavaBucket,
	598: Minecart,
	599: Saddle,
	600: Redstone,
	601: Snowball,
	602: OakBoat,
	603: Leather,
	604: MilkBucket,
	605: PufferfishBucket,
	606: SalmonBucket,
	607: CodBucket,
	608: TropicalFishBucket,
	609: Brick,
	610: ClayBall,
	611: SugarCane,
	612: Kelp,
	613: DriedKelpBlock,
	614: Bamboo,
	615: Paper,
	616: Book,
	617: SlimeBall,
	618: ChestMinecart,
	619: FurnaceMinecart,
	620: Egg,
	621: Compass,
	622: FishingRod,
	623: Clock,
	624: GlowstoneDust,
	625: Cod,
	626: Salmon,
	627: TropicalFish,
	628: Pufferfish,
	629: CookedCod,
	630: CookedSalmon,
	631: InkSac,
	632: RedDye,
	633: GreenDye,
	634: CocoaBeans,
	635: LapisLazuli,
	636: PurpleDye,
	637: CyanDye,
	638: LightGrayDye,
	639: GrayDye,
	640: PinkDye,
	641: LimeDye,
	642: YellowDye,
	643: LightBlueDye,
	644: MagentaDye,
	645: OrangeDye,
	646: BoneMeal,
	647: BlueDye,
	648: BrownDye,
	649: BlackDye,
	650: WhiteDye,
	651: Bone,
	652: Sugar,
	653: Cake,
	654: WhiteBed,
	655: OrangeBed,
	656: MagentaBed,
	657: LightBlueBed,
	658: YellowBed,
	659: LimeBed,
	660: PinkBed,
	661: GrayBed,
	662: LightGrayBed,
	663: CyanBed,
	664: PurpleBed,
	665: BlueBed,
	666: BrownBed,
	667: GreenBed,
	668: RedBed,
	669: BlackBed,
	670: Cookie,
	671: FilledMap,
	672: Shears,
	673: MelonSlice,
	674: DriedKelp,
	675: PumpkinSeeds,
	676: MelonSeeds,
	677: Beef,
	678: CookedBeef,
	679: Chicken,
	680: CookedChicken,
	681: RottenFlesh,
	682: EnderPearl,
	683: BlazeRod,
	684: GhastTear,
	685: GoldNugget,
	686: NetherWart,
	687: Potion,
	688: GlassBottle,
	689: SpiderEye,
	690: FermentedSpiderEye,
	691: BlazePowder,
	692: MagmaCream,
	693: BrewingStand,
	694: Cauldron,
	695: EnderEye,
	696: GlisteringMelonSlice,
	697: BatSpawnEgg,
	698: BeeSpawnEgg,
	699: BlazeSpawnEgg,
	700: CatSpawnEgg,
	701: CaveSpiderSpawnEgg,
	702: ChickenSpawnEgg,
	703: CodSpawnEgg,
	704: CowSpawnEgg,
	705: CreeperSpawnEgg,
	706: DolphinSpawnEgg,
	707: DonkeySpawnEgg,
	708: DrownedSpawnEgg,
	709: ElderGuardianSpawnEgg,
	710: EndermanSpawnEgg,
	711: EndermiteSpawnEgg,
	712: EvokerSpawnEgg,
	713: FoxSpawnEgg,
	714: GhastSpawnEgg,
	715: GuardianSpawnEgg,
	716: HorseSpawnEgg,
	717: HuskSpawnEgg,
	718: LlamaSpawnEgg,
	719: MagmaCubeSpawnEgg,
	720: MooshroomSpawnEgg,
	721: MuleSpawnEgg,
	722: OcelotSpawnEgg,
	723: PandaSpawnEgg,
	724: ParrotSpawnEgg,
	725: PhantomSpawnEgg,
	726: PigSpawnEgg,
	727: PillagerSpawnEgg,
	728: PolarBearSpawnEgg,
	729: PufferfishSpawnEgg,
	730: RabbitSpawnEgg,
	731: RavagerSpawnEgg,
	732: SalmonSpawnEgg,
	733: SheepSpawnEgg,
	734: ShulkerSpawnEgg,
	735: SilverfishSpawnEgg,
	736: SkeletonSpawnEgg,
	737: SkeletonHorseSpawnEgg,
	738: SlimeSpawnEgg,
	739: SpiderSpawnEgg,
	740: SquidSpawnEgg,
	741: StraySpawnEgg,
	742: TraderLlamaSpawnEgg,
	743: TropicalFishSpawnEgg,
	744: TurtleSpawnEgg,
	745: VexSpawnEgg,
	746: VillagerSpawnEgg,
	747: VindicatorSpawnEgg,
	748: WanderingTraderSpawnEgg,
	749: WitchSpawnEgg,
	750: WitherSkeletonSpawnEgg,
	751: WolfSpawnEgg,
	752: ZombieSpawnEgg,
	753: ZombieHorseSpawnEgg,
	754: ZombiePigmanSpawnEgg,
	755: ZombieVillagerSpawnEgg,
	756: ExperienceBottle,
	757: FireCharge,
	758: WritableBook,
	759: WrittenBook,
	760: Emerald,
	761: ItemFrame,
	762: FlowerPot,
	763: Carrot,
	764: Potato,
	765: BakedPotato,
	766: PoisonousPotato,
	767: Map,
	768: GoldenCarrot,
	769: SkeletonSkull,
	770: WitherSkeletonSkull,
	771: PlayerHead,
	772: ZombieHead,
	773: CreeperHead,
	774: DragonHead,
	775: CarrotOnAStick,
	776: NetherStar,
	777: PumpkinPie,
	778: FireworkRocket,
	779: FireworkStar,
	780: EnchantedBook,
	781: NetherBrick,
	782: Quartz,
	783: TntMinecart,
	784: HopperMinecart,
	785: PrismarineShard,
	786: PrismarineCrystals,
	787: Rabbit,
	788: CookedRabbit,
	789: RabbitStew,
	790: RabbitFoot,
	791: RabbitHide,
	792: ArmorStand,
	793: IronHorseArmor,
	794: GoldenHorseArmor,
	795: DiamondHorseArmor,
	796: LeatherHorseArmor,
	797: Lead,
	798: NameTag,
	799: CommandBlockMinecart,
	800: Mutton,
	801: CookedMutton,
	802: WhiteBanner,
	803: OrangeBanner,
	804: MagentaBanner,
	805: LightBlueBanner,
	806: YellowBanner,
	807: LimeBanner,
	808: PinkBanner,
	809: GrayBanner,
	810: LightGrayBanner,
	811: CyanBanner,
	812: PurpleBanner,
	813: BlueBanner,
	814: BrownBanner,
	815: GreenBanner,
	816: RedBanner,
	817: BlackBanner,
	818: EndCrystal,
	819: ChorusFruit,
	820: PoppedChorusFruit,
	821: Beetroot,
	822: BeetrootSeeds,
	823: BeetrootSoup,
	824: DragonBreath,
	825: SplashPotion,
	826: SpectralArrow,
	827: TippedArrow,
	828: LingeringPotion,
	829: Shield,
	830: Elytra,
	831: SpruceBoat,
	832: BirchBoat,
	833: JungleBoat,
	834: AcaciaBoat,
	835: DarkOakBoat,
	836: TotemOfUndying,
	837: ShulkerShell,
	838: IronNugget,
	839: KnowledgeBook,
	840: DebugStick,
	841: MusicDisc_13,
	842: MusicDiscCat,
	843: MusicDiscBlocks,
	844: MusicDiscChirp,
	845: MusicDiscFar,
	846: MusicDiscMall,
	847: MusicDiscMellohi,
	848: MusicDiscStal,
	849: MusicDiscStrad,
	850: MusicDiscWard,
	851: MusicDisc_11,
	852: MusicDiscWait,
	853: Trident,
	854: PhantomMembrane,
	855: NautilusShell,
	856: HeartOfTheSea,
	857: Crossbow,
	858: SuspiciousStew,
	859: Loom,
	860: FlowerBannerPattern,
	861: CreeperBannerPattern,
	862: SkullBannerPattern,
	863: MojangBannerPattern,
	864: GlobeBannerPattern,
	865: Barrel,
	866: Smoker,
	867: BlastFurnace,
	868: CartographyTable,
	869: FletchingTable,
	870: Grindstone,
	871: Lectern,
	872: SmithingTable,
	873: Stonecutter,
	874: Bell,
	875: Lantern,
	876: SweetBerries,
	877: Campfire,
	878: Honeycomb,
	879: BeeNest,
	880: Beehive,
	881: HoneyBottle,
	882: HoneyBlock,
	883: HoneycombBlock,
}

